### PR TITLE
MarkedCircularBuffer: don't used indices incorrectly

### LINKED ISSUE #836: MarkedCircularBuffer uses CircularBuffer indices wrongly
thanks to @JovanMilenkovic for reporting:

`MarkedCircularBuffer` relies on indices into `CircularBuffer` remaining valid after mutating operations. That's not legal and needs to change. `MarkedCircularBuffer` should just store an offset from the start/end.

### PR DESCRIPTION
**Pull request by weissi**
Motivation:

MarkedCircularBuffer was assuming that indices remain stable across
mutations, that's wrong.

Modifications:

Don't store the marked index but rather the offset from the start
instead.

Result:

- MarkedCircularBuffer uses indices correctly.
- fixes #836 (thanks for @JovanMilenkovic for finding this issue)
- will enable #835 to work properly

### CODE REVIEW

**Comment by normanmaurer** [comment]
@weissi shouldn't we also include a unit test ?

**Comment by weissi** [comment]
> @weissi shouldn't we also include a unit test ?

@normanmaurer there are plenty of them. We can't write a unit test yet that the use was incorrect before #835 lands in its final implementation

**Comment by JovanMilenkovic** [comment]
Give me a minute

**Comment by weissi** [comment]
@JovanMilenkovic there's no rush on your PR, it's not SemVer major breaking so you've got time :)

**Comment by JovanMilenkovic** [comment]
Pushed an update

**Comment by JovanMilenkovic** [comment]
Oh cool, I thought it's blocking you.

**Pull request merged**
