### PR TITLE
* refactored priority queue ==

### PR DESCRIPTION
**Pull request by adamnemecek**

### CODE REVIEW

**Comment by normanmaurer** [comment]
@adamnemecek Can you for this commit please use our commit template so it’s easier to understand for people why the change was done ?

Just amend the commit with the new message and force push

**Comment by adamnemecek** [comment]
Like this?

**Comment by normanmaurer** [comment]
@adamnemecek almost ... keep the motivation etc stuff. Like https://github.com/apple/swift-nio/commit/d74dda7439a8b53a429b9cd79f6a6075ec7f44f6

Sorry for nitpicking

**Comment by adamnemecek** [comment]
Now?

**Comment by normanmaurer** [comment]
@adamnemecek Perfect 👌

**Comment by normanmaurer** [comment]
@swift-nio-bot test this please

**Comment by airspeedswift** [comment]
If ` Array(lhs) == Array(rhs)` is the correct functionality, and those arrays are being constructed via the default initializer that creates an array by iterating the sequence, then `lhs.elementsEqual(rhs)` is what you want.

**Comment by normanmaurer** [comment]
@adamnemecek wdyt ? Can you add a unit test that shows that water the fix all is still fine ?

**Comment by normanmaurer** [comment]
@adamnemecek any update ?

**Comment by normanmaurer** [comment]
@Lukasa @weissi @airspeedswift PTAL

**Comment by adamnemecek** [comment]
wait that's not right. i did something wrong in git. or can you see the change? it should be lhs.count == rhs.count && lhs.elementsEqual(rhs)

**Comment by normanmaurer** [comment]
@adamnemecek nope

**Comment by adamnemecek** [comment]
ok now for realz tho

**Comment by airspeedswift** [comment]
The key question is whether to heaps with the same elements but created through insertions in a different order can produce heaps with storage in a different order (in a similar way that `Set` can). I don't... _think_ it can? But this probably needs to be determined by reasoning rather than testing since it might only ever happen in very edge cases the tests don't catch.

**Comment by adamnemecek** [comment]
So before submitted the PR, I thought they can then I thought about it and thought that they can't. Then you brought it up so I assumed that my original guess was correct. But now you are going back too :-). I think it's safer to assume they can be in different orders.

**Comment by normanmaurer** [comment]
@swift-nio-bot test this please

**Comment by normanmaurer** [comment]
@adamnemecek this looks good... That said would you mind to factor out the "case style changes" to another PR so this one only has the "==" change ?

**Comment by adamnemecek** [comment]
I'll split the changes up next time but if you could merge this in as is, I would really appreciate it.

**Comment by normanmaurer** [comment]
@weissi @Lukasa WDYT ?

**Comment by weissi** [comment]
Thanks for your PR @adamnemecek . Generally this looks really good, just two comments:

@adamnemecek / @airspeedswift The elements can be in different order, think for example only partially ordered things.

@adamnemecek I think this should be split up into two separate PRs, one for the `==` change and one for the `case` simplifications. Also would you mind removing the `*` at the beginning of the commit name?

**Comment by airspeedswift** [comment]
@weissi well in that case the current implementation is incorrect as well. but also `Comparable` is explicitly a [total order](https://github.com/apple/swift/blob/master/stdlib/public/core/Comparable.swift#L52). Partially ordered types shouldn't conform to `Comparable` – though you could have a version of this type that took a closure representing a partial ordering (instead of the current enum perhaps).

**Comment by weissi** [comment]
Thanks @airspeedswift , agreed

**Comment by normanmaurer** [comment]
I think we can close this one now as we already merged https://github.com/apple/swift-nio/pull/183

**Pull request closed without merging**
