### PR TITLE
Nest HTTPHeaderIterator inside HTTPHeader, un-erase makeIterator()

### PR DESCRIPTION
**Pull request by airspeedswift**
Similar to #91 and #93, but in this case the un-nested iterator was already internal, but there was use of a type-erased `AnyIterator` that seems like it could be eliminated. @weissi do you know the background for the type-erasure? Anything I'm missing?

Motivation:

Simplifies the code by putting the iterator in HTTPHeader's namespace.

Additionally, removing the type erasure should result in more performant code as `AnyIterator` is an optimization barrier. The type erasure did not appear to be adding an abstraction benefit.

Modifications:

Nested (internal) type `HTTPHeaderIterator` as `HTTPHeader.Iterator`
Explicit rather than inferred types for `Element` and `Iterator`.
Eliminated `AnyIterator` wrapper from `makeIterator()`
Added lower-priority version that still returns `AnyIterator` for source compatibility purposes.

Result:

Unless caller was explicitly typing the iterator, should have no noticeable impact other than performance.

### CODE REVIEW

**Comment by airspeedswift** [comment]
Similar to #91, a test could be added for the compatibility but at the cost of warnings when testing. This test passes:

```swift
    func testCompat() {
        let data = [("foo", "bar")]

        let headers = HTTPHeaders(data)
        let oldIt: AnyIterator = headers.makeIterator()

        while let (key,value) = oldIt.next() {
            XCTAssertEqual("foo", key)
            XCTAssertEqual("bar", value)
        }
        
        let newIt = headers.makeIterator()
        XCTAssert(type(of: newIt) == HTTPHeaders.Iterator.self)
        XCTAssert(type(of: oldIt) != HTTPHeaders.Iterator.self)
    }
```

**Comment by airspeedswift** [comment]
@Lukasa sure, no rush

@weissi let me know when you're back and I'll rebase

**Comment by weissi** [comment]
@airspeedswift and @Lukasa I can confirm that the type-erasure was not deliberate, no idea what I was thinking back then, sorry. Thanks for this patch and from my side please go ahead.

**Comment by Lukasa** [comment]
Cool, go ahead and rebase @airspeedswift.

**Pull request merged**
