### PR TITLE
Throw an appropriate error from the writer when the channel closed

### PR DESCRIPTION
**Pull request by FranzBusch**
# Motivation
Currently, when the channel closes and a user tries to write something the writer throws an `AlreadyFinished` error. This error can also be thrown when calling `finish` on the writer and then trying to call `write` again. This makes it hard to distinguish if the thrown error was due to the channel being closed or due to a business logic error in handling the writer.

# Modification
This PR finishes the writer with a `ChannelError.ioOnClosedChannel` if the writer gets finished to due a channel inactive or handler removed.

# Result
Users can now distinguish if they did something wrong with the writer or if the channel closed.

### CODE REVIEW

**Review by Lukasa — APPROVED** [review]
Nice, this looks like a good improvement.

**Review by ali-ahsan-ali — APPROVED** [review]

**Comment by FranzBusch** [comment]
@swift-server-bot test this please

**Comment by FranzBusch** [comment]
@swift-server-bot test this please

**Comment by FranzBusch** [comment]
@swift-server-bot test this please

**Pull request merged**
