### PR TITLE
Create ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by weissi**
Added ISSUE_TEMPLATE.md
Motivation:

It's great if the GitHub issues come prefilled with a template.

Modifications:

Added a template very similiar to the commit one but md.

Result:

hopefully issues that are easier to action :)

### CODE REVIEW

**Comment by normanmaurer** [comment]
@weissi please se our commit template

**Comment by weissi** [comment]
@normanmaurer as in verbatim? Changed it to that.

**Comment by Lukasa** [comment]
No, he means for your commit. :wink:

**Comment by weissi** [comment]
haha #slow

**Comment by weissi** [comment]
@normanmaurer done

**Pull request merged**
