### PR TITLE
improve ChannelPipeline debug print

### PR DESCRIPTION
**Pull request by tanner0101**
This PR improves `ChannelPipeline`'s `CustomDebugStringConvertible` conformance:

```swift
print(someChannel.pipeline)
``` 

```
ChannelPipeline[0x0000000000000000]:
                     [I] ↓↑ [O]
 <incoming handler type> ↓↑                         [<name>]
                         ↓↑ <outgoing handler type> [<name>]
   <duplex handler type> ↓↑ <duplex handler type>   [<name>]
```

See #848 for more information.

### CODE REVIEW

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Comment by tomerd** [comment]
@swift-nio-bot test this please

**Comment by weissi** [comment]
@tanner0101 you'll need to run `scripts/generate_linux_tests.rb` here :)

**Comment by tanner0101** [comment]
@weissi done :)

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Pull request merged**
