### PR TITLE
Change unnecessary functions to variables 

### PR DESCRIPTION
**Pull request by BasThomas**
Changes some unnecessary functions to computed variables.

### Motivation:

The changed functions do not have any side effects and therefore better convey intent when being a simple computed variable.

### Modifications:

- `func markedElementIndex() -> Int?` to `var markedElementIndex: Int?`
- `func markedElement() -> E?` to `var markedElement: E?`
- `func hasMark() -> Bool` to `var hasMark: Bool`

### Result:

⚠️ **This is a breaking change and needs a major version bump** ⚠️

Changes some unncessary functions to computed variables.

Opened in favor of #88

### CODE REVIEW

**Comment by BasThomas** [comment]
ping @weissi

**Comment by BasThomas** [comment]
Of course, done!

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by BasThomas** [comment]
My pleasure!

**Pull request merged**
