### PR TITLE
* removed trailing whitespace

### PR DESCRIPTION
**Pull request by adamnemecek**

### CODE REVIEW

**Comment by normanmaurer** [comment]
test this please

**Comment by adamnemecek** [comment]
Me?

**Comment by normanmaurer** [comment]
@adamnemecek nope its for the ci :) ... Sorry for the confusion.

**Comment by adamnemecek** [comment]
Ah ok.

**Comment by tomerd** [comment]
@swift-nio-bot test this please

**Comment by normanmaurer** [comment]
@swift-nio-bot test this please

**Comment by normanmaurer** [comment]
@swift-nio-bot test this please

**Comment by normanmaurer** [comment]
@adamnemecek thanks!

**Pull request merged**
