### PR TITLE
rename Channel._unsafe to Channel._channelCore

### PR DESCRIPTION
**Pull request by weissi**
Motivation:

_unsafe is non-descriptive

Modifications:

- rename Channel._unsafe to Channel._channelCore

Result:

clearer API

### CODE REVIEW

**Comment by Lukasa** [comment]
_ChannelCore *is* public API: implementing it is necessary to implement a new Channel.

**Comment by weissi** [comment]
@Lukasa yeah, it's implementor's public API but not for users. But I think you're right. Maybe we should leave the type name alone (ie. `ChannelCore`) and just rename the property from `_unsafe` to `_channelCore`. What do you think?

**Comment by Lukasa** [comment]
I think that's a good plan. 👍

**Comment by weissi** [comment]
@Lukasa updated, thanks

**Pull request merged**
