### PR TITLE
Remove useless instance variables in the SelectableEventLoop

### PR DESCRIPTION
**Pull request by thomas-gill-0xff**
Motivation:

Less code we have - less bugs we have.
The fix remove few lines of code keeping the same functionality.

Modifications:

Just remove some useless instance variables.

Result:

Less code.

### CODE REVIEW

**Comment by dnadoba** [comment]
@swift-nio-bot test this please

**Comment by dnadoba** [comment]
@swift-server-bot test this please

**Review by Lukasa — APPROVED** [review]
Nice clean up, thanks!

**Comment by Lukasa** [comment]
@swift-server-bot test this please

**Pull request merged**
