### PR TITLE
Refactors generate_linux_tests script

### PR DESCRIPTION
**Pull request by FrankKair**
### Motivation:

`generate_linux_tests.rb` is written in a non idiomatic way.

### Modifications:

I used [Rubocop](https://github.com/bbatsov/rubocop) to refactor the code.

### Result:

A more idiomatic Ruby script.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@tomerd please check

**Comment by tomerd** [comment]
thanks @FrankKair! on the surface looks good, please confirm you've tested it produces same results for the different use cases

**Comment by FrankKair** [comment]
Yes, I tested it on both branches and it produced the same output 😊👍🏻

**Comment by FrankKair** [comment]
Done! ✅

**Comment by FrankKair** [comment]
@tomerd Any idea on why this failed the test after the rebase?

**Comment by tomerd** [comment]
@weissi @normanmaurer @Lukasa looks like ur leak detector got tripped

```
00:02:50.359 Test Case 'EchoServerClientTest.testPendingReadProcessedAfterWriteError' started at 2018-03-26 18:59:31.820
00:02:50.359 Fatal error: leaking promise created at (file: "/code/Sources/NIO/ChannelInvoker.swift", line: 171): file /code/Sources/NIO/ChannelInvoker.swift, line 171
00:02:50.360 Current stack trace:
00:02:50.360 0    libswiftCore.so                    0x00007fdcf5414f90 _swift_stdlib_reportFatalErrorInFile + 221
00:02:50.361 1    libswiftCore.so                    0x00007fdcf511e330 closure #1 in closure #1 in closure #1 in _assertionFailure(_:_:file:line:flags:) + 284
00:02:50.362 2    libswiftCore.so                    0x00007fdcf53be9a1 <unavailable> + 4155809
00:02:50.362 3    libswiftCore.so                    0x00007fdcf53d5059 <unavailable> + 4247641
00:02:50.363 4    libswiftCore.so                    0x00007fdcf511dc0b <unavailable> + 1399819
00:02:50.363 5    libswiftCore.so                    0x00007fdcf53376b9 <unavailable> + 3602105
00:02:50.363 6    libswiftCore.so                    0x00007fdcf537579f <unavailable> + 3856287
00:02:50.364 7    libswiftCore.so                    0x00007fdcf511dc0b <unavailable> + 1399819
00:02:50.364 8    libswiftCore.so                    0x00007fdcf52b77a0 specialized _assertionFailure(_:_:file:line:flags:) + 144
00:02:50.365 9    swift-nioPackageTests.xctest       0x00000000004c53fc <unavailable> + 807932
00:02:50.366 10   swift-nioPackageTests.xctest       0x00000000004c555c <unavailable> + 808284
00:02:50.366 11   swift-nioPackageTests.xctest       0x000000000055812c <unavailable> + 1409324
00:02:50.367 12   swift-nioPackageTests.xctest       0x000000000055802d <unavailable> + 1409069
00:02:50.367 13   swift-nioPackageTests.xctest       0x00000000004c4fa1 <unavailable> + 806817
00:02:50.368 14   swift-nioPackageTests.xctest       0x00000000004c558f <unavailable> + 808335
00:02:50.368 15   libswiftCore.so                    0x00007fdcf53dc1cb <unavailable> + 4276683
00:02:50.369 16   swift-nioPackageTests.xctest       0x000000000049588f <unavailable> + 612495
00:02:50.369 17   libswiftCore.so                    0x00007fdcf53dc1cb <unavailable> + 4276683
00:02:50.370 18   swift-nioPackageTests.xctest       0x00000000004bd239 <unavailable> + 774713
00:02:50.370 19   swift-nioPackageTests.xctest       0x00000000004bd261 <unavailable> + 774753
00:02:50.371 20   libswiftCore.so                    0x00007fdcf53dc1cb <unavailable> + 4276683
00:02:50.371 21   libswiftCore.so                    0x00007fdcf53dda5c <unavailable> + 4282972
00:02:50.372 22   libswiftCore.so                    0x00007fdcf515d740 _ContiguousArrayStorage.__deallocating_deinit + 57
00:02:50.372 23   libswiftCore.so                    0x00007fdcf53dc1cb <unavailable> + 4276683
00:02:50.373 24   swift-nioPackageTests.xctest       0x00000000004b7c01 <unavailable> + 752641
00:02:50.373 25   swift-nioPackageTests.xctest       0x00000000004b76af <unavailable> + 751279
00:02:50.374 26   swift-nioPackageTests.xctest       0x00000000004bab68 <unavailable> + 764776
00:02:50.374 27   swift-nioPackageTests.xctest       0x00000000004bf9ac <unavailable> + 784812
00:02:50.375 28   swift-nioPackageTests.xctest       0x00000000004bb12f <unavailable> + 766255
00:02:50.375 29   swift-nioPackageTests.xctest       0x000000000055754a <unavailable> + 1406282
00:02:50.376 30   swift-nioPackageTests.xctest       0x00000000005564a1 <unavailable> + 1402017
00:02:50.376 31   swift-nioPackageTests.xctest       0x0000000000556549 <unavailable> + 1402185
00:02:50.377 32   libpthread.so.0                    0x00007fdcf4db0184 <unavailable> + 33156
00:02:50.377 33   libc.so.6                          0x00007fdcf3385fd0 clone + 109
```

@swift-nio-bot test this please, i think this is flakiness

**Comment by weissi** [comment]
@tomerd thanks, filed as #246 for now

**Comment by tomerd** [comment]
@swift-nio-bot test this please

**Comment by tomerd** [comment]
@swift-nio-bot test this please

**Pull request merged**
