### PR TITLE
build: bump tools version to 5.3

### PR DESCRIPTION
**Pull request by compnerd**
This is needed to gain access to Windows support.

_[One line description of your change]_

### Motivation:

_[Explain here the context, and why you're making that change. What is the problem you're trying to solve.]_

### Modifications:

_[Describe the modifications you've done.]_

### Result:

_[After your change, what will change.]_

### CODE REVIEW

**Comment by 0xTim** [comment]
Can't this be achieved with a `Package@swift-5.3.swift` manifest?

**Review by Lukasa — CHANGES_REQUESTED** [review]
Yeah, we cannot unconditionally bump the tools version, as it amounts to dropping support for 5.0 through 5.2. A new `Package.swift@5.3` is a workable alternative.

**Comment by PeterAdams-A** [comment]
I don't think we can really take this approach as it breaks previous versions of swift.

**Comment by compnerd** [comment]
Okay, I'll fork the current `package.swift` then.  Does s-p-m pickup the file automatically?  Seems that the same argument as with CMake applies to keeping the old definition: you have two definitions.

**Comment by Lukasa** [comment]
Yes, SPM will pick up the appropriate version.

**Comment by Lukasa** [comment]
I think we agreed we don't need this?

**Comment by compnerd** [comment]
I think for now we do not.  We can always revisit this if necessary.

**Pull request closed without merging**
