### PR TITLE
fix 5.2 builds

### PR DESCRIPTION
**Pull request by tomerd**
motivation: tsan is broken on ubuntu 18.04.use 16.04 so 5.2 build can pass

changes:
* change 5.2 docker setup to use 16.04 instead of 18.04
* add the ability to pipe arguments to the integration tests via the docker setup
* skip tests_02 integration tests suite since it broken on 5.2 (swift-pm issue?)

### CODE REVIEW

**Comment by tomerd** [comment]
@weissi looks like some of the integration tests are failing, do we need to adjust some of the values?

**Comment by Lukasa** [comment]
I think the values are fine, it's the syscall integration test that's failing. We expect to see the process killed with `SIGILL` but we aren't. I suspect the problem is here:

```
02:51:25 /tmp/.swift-nio-syscall-wrappers-sh-test_53mM2l/syscallwrapper/Sources/syscallwrapper/System.swift:27:8: error: no such module 'CNIOLinux'
```

@weissi Looks like something in the integration tests isn't playing nice with the 5.2 snapshots.

**Comment by weissi** [comment]
@Lukasa cool, will look into it today

**Comment by Lukasa** [comment]
I wonder if this is related to the fact that CNIOLinux in those tests is a symlink.

**Comment by Lukasa** [comment]
Yeah, I can reproduce this with any SwiftPM project that contains a symlink to the source files for a module. We also get this warning:

```
warning: Source files for target Test should be located under /root/tmp/Sources/Test
```

**Comment by Lukasa** [comment]
SwiftPM bug: https://bugs.swift.org/browse/SR-12094

**Comment by tomerd** [comment]
@weissi updated the PR to use 16.04 and skip offending tests, ptal

**Comment by tomerd** [comment]
```
/code/Tests/NIOTests/SyscallAbstractionLayer.swift:511: error: SALChannelTest.testBasicRead : XCTAssertNoThrow failed: threw error "TimeoutError(description: "u2k")" -
```

@swift-server-bot test this please

**Comment by tomerd** [comment]
```
00:17:15.274 Running test suite 'tests_04_performance'
00:17:15.284 Running test 'test_01_allocation_counts.sh'... FAILURE (9)
```

@weissi I think this one is for you

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
more of 
```
00:08:39.332 /code/Tests/NIOTests/SyscallAbstractionLayer.swift:511: error: SALChannelTest.testBasicRead : XCTAssertNoThrow failed: threw error "TimeoutError(description: "u2k")" - 
``` 
seem to be flaky on both 5.1 and 5.2?

**Comment by weissi** [comment]
Thanks @tomerd , I’ll look into all of these issues

**Comment by weissi** [comment]
flakes should be fixed with #1364

**Comment by weissi** [comment]
superseded by #1366 which contains the changes from this PR.

**Pull request closed without merging**
