### PR TITLE
dnm: test pr

### PR DESCRIPTION
**Pull request by tomerd**
_[One line description of your change]_

### Motivation:

_[Explain here the context, and why you're making that change. What is the problem you're trying to solve.]_

### Modifications:

_[Describe the modifications you've done.]_

### Result:

_[After your change, what will change.]_

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
@weissi this is failing on TSAN issue with 18.04. do you want to disable TSAN for the until the upstream issue is addressed?

**Comment by weissi** [comment]
Yes, sounds good @tomerd

**Comment by tomerd** [comment]
https://github.com/apple/swift-nio/pull/1360

**Pull request closed without merging**
