### PR TITLE
add make-single-file-spm

### PR DESCRIPTION
**Pull request by weissi**
Motivation:

make-single-file-spm is a simple bash script that can turn a single file
into a SwiftPM project with multiple modules (all defined in a single
file with special markers such as `// MODULE: Foo`. This is mostly
useful for performance evaluation of Swift becuase in almost all cases,
you'll need multiple modules which is quite a bit of work to set up.

Modifications:

Add make-single-file-spm

Result:

More useful scripts in the NIO repo.

### CODE REVIEW

**Comment by weissi** [comment]
CC @aciidb0mb3r is there a bug already about programmatic creation of SwiftPM projects? I thought someone was working on that a while ago.

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by aciidb0mb3r** [comment]
I am not sure what bug are you referring to.

**Comment by weissi** [comment]
@aciidb0mb3r where someone could use something like

```
swift package-edit new --name MyPackage
swift package-edit add-module --name MyModule
swift package-edit add-module --name OtherModule --dependency MyModule
swift package-edit add-executable --name run --module MyModule
```

or something like that to programmatically create a `Package.swift` instead of my horrible bash to in this PR :)

**Comment by aciidb0mb3r** [comment]
Aha! Yeah, that's not a thing right now.

**Pull request merged**
