### PR TITLE
Fail promise in MessageToByteHandler write error cases

### PR DESCRIPTION
**Pull request by wlisac**
This fails the `write` promise in `MessageToByteHandler` for all write error cases.

### Motivation:
The promise is leaked if the encoder fails or if the handler is an error state.

### Modifications:
Call `fail` on the `write` promise if the encoder fails or if the handler is an error state.

### Result:
The `write` promise will now fail in all error cases.

### Additional Information
I debated on if the promise should be failed before or after `context.fireErrorCaught`. I found some prior art, here: https://github.com/apple/swift-nio-http2/blob/master/Sources/NIOHTTP2/HTTP2ToHTTP1Codec.swift#L98

I also debated on if the promise should be failed before or after the state in the handler has been changed to `error`. I decided to fail it after changing the state to `error` since I was concerned about the promise failing, calling write again, and triggering another error before the first error state was set.

### CODE REVIEW

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by wlisac** [comment]
Thanks @Lukasa. I added a test case that exercises both code paths. 

I considered breaking it into two tests, but they looked almost identical. Still happy to break into two distinct tests if you'd prefer.

As an aside, while I was looking at related tests, it looks like there may be an issue with `MessageToByteEncoderTest`. 

Notice that `testEncoder` ignores the passed in handler. If you honor the passed in handler, then there's an assertion failure that gets triggered.
```
XCTAssertEqual(MemoryLayout<Int32>.size, 256)
```

I didn't want to bloat this PR with additional changes, but I wanted to call it out in case something should be changed there :)

Appreciate the review!

– Will

**Comment by Lukasa** [comment]
Yeah, that test is perplexing. Thanks for not placing the changes into this patch, I'd much rather have a fixup for those tests in a separate PR.

Naturally, that assertion will always fail, as the size of an Int32 is pretty clearly 4. That invalid assertion has been in the code a long time so I don't know what it was intended to test, but I think it was actually _supposed_ to assert on the capacity of the provided buffer. This makes sense if you look at the version of the file from before #868:  https://github.com/apple/swift-nio/blob/cde067e603c0569d522f0dc0bd9d8f804ba40b26/Tests/NIOTests/CodecTest.swift#L1155-L1185

In this code, it's clear that the purpose of the twin tests was to validate that you could override the default allocator. That test is no longer useful as you now _cannot_ override the default allocator, so we should probably just collapse that test down to one.

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Pull request merged**
