### PR TITLE
add two ELF.reduce benchmarks

### PR DESCRIPTION
**Pull request by weissi**
Motivation:

As #1054 shows, we have some low-hanging performance fruit regarding
off-EventLoop future reduces. We should quantify those.

Modifications:

Add benchmarks to quantify the potential wins.

Result:

More benchmarks.

### CODE REVIEW

**Comment by weissi** [comment]
@swift-nio-bot test perf please

**Comment by weissi** [comment]
@tomerd thanks so much! Great job on even supporting added new benchmarks 💜

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by weissi** [comment]
CI is sad

```
07:59:30 Checking public API breakages from master to b697caf33729446aa837a0a3e19bcc05459e3d8d
07:59:30 fatal: reference is not a tree: b697caf33729446aa837a0a3e19bcc05459e3d8d
07:59:31 Build step 'Execute shell' marked build as failure
07:59:31 $ ssh-agent -k
```

retrying

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Pull request merged**
