### PR TITLE
better wait on EventLoop detection

### PR DESCRIPTION
**Pull request by weissi**
Motivation:

It's important that in NIO programs you don't call
EventLoopFuture.wait() on an EventLoop. We previously had some detection
built in but we can do better.

Modifications:

Detect wait() called on any of MultiThreadedEventLoopGroup's EventLoops.

Result:

Quicker and more deterministic detection if wait() abuse.

### CODE REVIEW

**Comment by Lukasa** [comment]
Is it worth us defining protocols we can let `EventLoop` and `EventLoopGroup`s opt in to that would allow us to make this more general? `wait` is not a high-performance call anyway, so the overhead of the indirection isn't necessarily a big deal, and it will let us extend this checking to things like `NIOTSEventLoopGroup`.

**Comment by weissi** [comment]
@Lukasa sounds good to me! The only thing we've got is the `EventLoop` `self` though, right? How would we get from there to the group to ask it if we're in any of those?

**Comment by Lukasa** [comment]
Yeah, we'd need two protocols. One would need to be a protocol that extends `EventLoop` with a `parentGroup` property, then we could have the one on the group that tells you whether you're currently running in an event loop context.

**Comment by weissi** [comment]
this hit #548 too (fixed in #555)

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Comment by weissi** [comment]
@Lukasa do you want that those new protocols before this work or should we merge like this and later improve how it's done so NIOTS can benefit too?

**Comment by Lukasa** [comment]
Let's merge this now, and we can enhance this with new protocols later.

**Pull request merged**
