### PR TITLE
Replace ByteBufferTest use of deprecated "withUnsafeBytes" with new API

### PR DESCRIPTION
**Pull request by JovanMilenkovic**
Motivation:

Remove the only warning in the project.

Modifications:

Use new withUnsafeBytes API.

Result:

The project will have no warnings.

### CODE REVIEW

**Comment by Lukasa** [comment]
Leaving this for @weissi because I haven't seen the deprecation warning that is apparently being emitted here.

**Comment by JovanMilenkovic** [comment]
Ah right, I knew there had to be a reason.

**Comment by weissi** [comment]
@millenomi should we file a bug that Linux diverges from Darwin here?

**Comment by millenomi** [comment]
No need; I’m fast-tracking https://github.com/apple/swift-corelibs-foundation/pull/1813 which is the implementation you’re looking for.

**Comment by millenomi** [comment]
Also: https://github.com/apple/swift-corelibs-foundation/pull/1853

**Comment by millenomi** [comment]
Upstream is merged.

**Comment by weissi** [comment]
thank you! Merged with #786

**Pull request closed without merging**
