### PR TITLE
Attempt to write WS header in user buffer.

### PR DESCRIPTION
**Pull request by Lukasa**
Motivation:

In some cases it may be possible to write the (usually small) web socket
frame header to the buffer provided by the user. If we do this we can
avoid an extra pipeline traversal for the small write. This is only
going to be a performance win in cases where we can avoid a
copy-on-write operation on the buffer, but if we can then it's a useful
small win to achieve.

Modifications:

- Refactored the WebSocketFrameEncoder to potentially prepend the frame
    header.
- Added a missing @inlinable attribute.
- Tests.

Result:

Potentially improved performance.

### CODE REVIEW

**Comment by Lukasa** [comment]
@swift-nio-bot test perf please

**Comment by Lukasa** [comment]
Yup, so this regresses allocations in some of the allocation counter tests because it adds some CoWs. Based on the performance results above the cost of the CoW is very similar to the cost of a shortish pipeline walk, so we probably only want to do this if we avoid a CoW. Sadly we don't have tools for that right now.

@weissi do we think it's worth adding an API for asking whether a BB modification might CoW?

**Comment by weissi** [comment]
@Lukasa I think it's worth to add that API. 

```
mutating func canBeWrittenToSwiftly() -> Bool { ... }
```

? :P

**Comment by Lukasa** [comment]
@weissi Do you think it's worth adding that API irregardless of this patch? If so, we should consider it a separate-but-gating patch here.

**Comment by weissi** [comment]
@Lukasa I think that'd be a useful API anyway, I'm happy with an extra PR or in this PR, up to you.

**Comment by Lukasa** [comment]
If we think it's a useful API anyway we should have a separate patch.

**Comment by Lukasa** [comment]
@swift-nio-bot test perf please

**Comment by Lukasa** [comment]
This is ready for review.

**Pull request merged**
