### PR TITLE
Allow to set RemoveAfterUpgradeStrategy on HTTPResponseDecoder

### LINKED ISSUE #741: payload immediately in the web socket upgrade response always gets lost
### Expected behavior

- NIO allows to forward 'left over' bytes trailing the server's upgrade response when NIO acts as an HTTP client

### Actual behavior

- NIO just drops them on the floor
- the only initialiser that `HTTPResponseDecoder` offers today sets [`leftOverBytesStrategy: .dropBytes`](https://github.com/apple/swift-nio/blob/f38984d80efd8548e9df6e3edba6193dbc71be54/Sources/NIOHTTP1/HTTPDecoder.swift#L185-L187)

### Steps to reproduce

Different options:

#### @MrLotU's repro:
1. create a bot here:  https://discordapp.com/developers/applications/ 
2. copy the token
3. put it in `Sources/NIOWSTryoutExample/main.swift`  replacing `"token"`
4. run the program

#### pre fabricated response

```
HTTP/1.1 101 Switching Protocols
Date: Mon, 07 Jan 2019 15:54:00 GMT
Connection: upgrade
Set-Cookie: __cfduid=XXXX; expires=Tue, 07-Jan-20 15:53:59 GMT; path=/; domain=.discord.gg; HttpOnly
sec-websocket-accept: XXXX
upgrade: websocket
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 495799b4eab30cc5-LHR

Å_{"t":null,"s":null,"op":10,"d":{"heartbeat_interval":41250,"_trace":["gateway-prd-main-0vfv"]}}
```

or as base 64:

```
SFRUUC8xLjEgMTAxIFN3aXRjaGluZyBQcm90b2NvbHMNCkRhdGU6IE1vbiwgMDcgSmFuIDIwMTkgMTU6NTQ6MDAgR01UDQpDb25uZWN0aW9uOiB1cGdyYWRlDQpTZXQtQ29va2llOiBfX2NmZHVpZD1YWFhYOyBleHBpcmVzPVR1ZSwgMDctSmFuLTIwIDE1OjUzOjU5IEdNVDsgcGF0aD0vOyBkb21haW49LmRpc2NvcmQuZ2c7IEh0dHBPbmx5DQpzZWMtd2Vic29ja2V0LWFjY2VwdDogWFhYWA0KdXBncmFkZTogd2Vic29ja2V0DQpFeHBlY3QtQ1Q6IG1heC1hZ2U9NjA0ODAwLCByZXBvcnQtdXJpPSJodHRwczovL3JlcG9ydC11cmkuY2xvdWRmbGFyZS5jb20vY2RuLWNnaS9iZWFjb24vZXhwZWN0LWN0Ig0KU2VydmVyOiBjbG91ZGZsYXJlDQpDRi1SQVk6IDQ5NTc5OWI0ZWFiMzBjYzUtTEhSDQoNCoFfeyJ0IjpudWxsLCJzIjpudWxsLCJvcCI6MTAsImQiOnsiaGVhcnRiZWF0X2ludGVydmFsIjo0MTI1MCwiX3RyYWNlIjpbImdhdGV3YXktcHJkLW1haW4tMHZmdiJdfX0NCg==
```

### SwiftNIO version/commit hash

1.9.0

### Swift & OS version (output of `swift --version && uname -a`)

swift 4.2.1 on macOS

### PR DESCRIPTION
**Pull request by MrLotU**
Fixes #741 

I added in the default argument so this can be merged without any other changes being necessary anywhere else.

Created PR on branch nio-1.12 because IMO it's a bug fix and should be included in a swift 4.2 release.

### CODE REVIEW

**Comment by MrLotU** [comment]
Not at all! I'll get on it 😄

**Comment by MrLotU** [comment]
@Lukasa Requested changes are implemented! I also back-ported your changes from #745 so they can be in NIO 1.12, if you'd like this in a separate PR, I'll remove them again.

**Comment by MrLotU** [comment]
All cleaned up! Thanks for the input @Lukasa

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
@weissi Are you happy with shipping a 1.13 release?

**Comment by MrLotU** [comment]
Just to check, 1.13 would still support Swift 4.2 right? With nio 2.0 being the first release that needs Swift 5

**Comment by Lukasa** [comment]
If we ship a 1.13 it'll still support Swift 4.2, yes. We just can't ship this as a 1.12.1.

**Comment by MrLotU** [comment]
Cool! Just to be sure, can see that a patch is not enough :)

**Comment by weissi** [comment]
@MrLotU do you mind re-opening this PR targeting `master`? If/when we do a 1.13 release we'd need to then have this target the `nio-1.13` branch.

**Comment by MrLotU** [comment]
👍

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Comment by weissi** [comment]
@Lukasa please ignore the green tick here, that's from testing it against the old `nio-1.12` branch AFAIK. We need to re-run tomorrow when CI is set up for 1.13

**Comment by MrLotU** [comment]
Makes me think GH should add a way to dismiss tests, like how you can dismiss reviews

**Comment by MrLotU** [comment]
@weissi I can commit a space or something to reset it if you really want to

**Comment by weissi** [comment]
@MrLotU so usually it dismisses them as soon as the branch has moved on. So it should've dismissed these here I think. Unless obviously it happens to have tested against the SHA that is currently `nio-1.13`...

**Comment by weissi** [comment]
no,

```
12:21:02  > git checkout -f ab186407b5f476757c85d2099c47f5fd704fc515
12:21:02 Commit message: "Merge 7b00ddb4804d2a939fe18c2e6443be91879ea452 into 37457897d97c8efcb4d23dba75937401730eabea"
```

hmm, I think this is a github bug

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Pull request merged**
