### PR TITLE
Tail allocate mutex and a generic value using ManagedBuffer

### PR DESCRIPTION
**Pull request by asdf-bro**
### Motivation:

Currently, NIOLock and NIOLockedValueBox incur unnecessary allocation and indirection costs.

### Modifications:

- Create namespace `LockOperations` for organization
- Create `LockStorage<Value>`, a subclass of `ManagedBuffer<LockPrimitive, Value>`
- Store the mutex as the header and the generic value as the first and only element
- Update NIOLock and NIOLockedValueBox to use LockStorage

### Result:

- Optimal lock and value memory layout
- Fewer allocations and less indirection
- Code generation is excellent (screenshot attached)

Screenshot 2023-01-13 at 11 35 49 AM

### CODE REVIEW

**Review by Lukasa — APPROVED** [review]
This looks like a fantastic patch, from my perspective it seems totally reasonable! Tagging @weissi for extra eyes though.

**Comment by Lukasa** [comment]
@swift-server-bot test this please

**Comment by asdf-bro** [comment]
This could also be structured such that LockStorage contains only `create` and `deinit`.  The four other methods could be implemented directly in either NIOLock or NIOLockedValueBox.

**Comment by Lukasa** [comment]
@swift-server-bot test this please

**Comment by Lukasa** [comment]
@swift-server-bot test this please

**Comment by Lukasa** [comment]
I've updated the allocation counter limits to take account of the reduced allocations. It's easier for me to do this because I can scrape the results from CI.

**Comment by Lukasa** [comment]
@swift-server-bot test this please

**Comment by Lukasa** [comment]
Thanks for this! :sparkles:

**Pull request merged**
