### PR TITLE
add Swift 5.5 job

### PR DESCRIPTION
**Pull request by weissi**

### CODE REVIEW

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
There are no nightly 5.5 docker images at the moment. We need to either get them to come into existence or disable the 5.5 job until they do.

**Review by Lukasa — CHANGES_REQUESTED** [review]
Requesting changes for the broken 5.5 job.

**Comment by yim-lee** [comment]
Disabled the 5.5. job

**Comment by buttaface** [comment]
I'm seeing problems compiling the tests with a recent official trunk snapshot build of the toolchain on linux:
```
> ~/src/swift-DEVELOPMENT-SNAPSHOT-2021-05-26-a-centos8/usr/bin/swift build --build-tests -j 2
/home/butta/swift-nio/Tests/NIOHTTP1Tests/TestUtils.swift:276:25: error: value of type 'sockaddr_in' has no member 'addressDescription'
            return addr.addressDescription()
                   ~~~~ ^~~~~~~~~~~~~~~~~~
/home/butta/swift-nio/Tests/NIOHTTP1Tests/TestUtils.swift:279:25: error: value of type 'sockaddr_in6' has no member 'addressDescription'
            return addr.addressDescription()
                   ~~~~ ^~~~~~~~~~~~~~~~~~
```
Swift 5.4 builds the exact same commit 43fa768 without a problem, so there appears to have been a regression somewhere.

**Comment by Lukasa** [comment]
This appears to be a compiler error, as that method is made available in an extension. Can you report this at bugs.swift.org?

**Comment by buttaface** [comment]
Sure.

**Comment by buttaface** [comment]
Looks like @weissi already reported it: SR-14268 and SR-14590.

**Comment by Lukasa** [comment]
@yim-lee I _believe_ the 5.5 builds should be able to be turned back on with the subsequent changes made in this patch.

**Review by Lukasa — APPROVED** [review]

**Comment by yim-lee** [comment]
@swift-nio-bot test this please

**Comment by yim-lee** [comment]
The 5.5 job was enabled but didn't get triggered for some reason. Should be ok now.

**Review by Lukasa — APPROVED** [review]

**Pull request merged**
