### PR TITLE
NIO: excise UDS support for Windows

### PR DESCRIPTION
**Pull request by compnerd**
This removes support for Unix Domain Sockets from NIO on Windows.
Although Windows 10.17063 introduced basic support for UDS, the support
is incomplete and has differences from the tradtional UDS sockets in
terms of behaviour.  Excise the support initially to get NIO to build on
Windows.

_[One line description of your change]_

### Motivation:

_[Explain here the context, and why you're making that change. What is the problem you're trying to solve.]_

### Modifications:

_[Describe the modifications you've done.]_

### Result:

_[After your change, what will change.]_

### CODE REVIEW

**Comment by compnerd** [comment]
One question that comes to mind: should this be a general option rather than platform conditional?  I imagine that WASM may not implement UDS either and so more than just windows would want the `UDS` support made optional.

**Comment by Lukasa** [comment]
> I imagine that WASM may not implement UDS either and so more than just windows would want the UDS support made optional.

WASM will want a lot more removed than just UDS, I think: NIO won't function at all on WASM as it relies on far too much of the system.

When WASM becomes something we really want to worry about we may need to consider a substantial refactor of the APIs. In particular, we probably will need to separate the bits of NIO that are truly platform agnostic (things like protocols, `ChannelPipeline`, `ChannelHandler`, various helper objects) from the things that are actually secretly "NIOPOSIX" (`SelectableEventLoop`, `MultithreadedEventLoopGroup`, and so-on).

I don't think we want to go too far down that road today, because it's a pretty substantial breaking change, but if we want to get serious about WASM it'll necessarily come up.

**Comment by Lukasa** [comment]
I'm marking this as a Semver patch because, well, we never worked on Windows before so this can't break existing APIs.

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Pull request merged**
