### PR TITLE
ByteBuffer: reduce unnecessary bounds & under/overflow checks

### PR DESCRIPTION
**Pull request by weissi**
Motivation:

ByteBuffer is quite core to NIO programs' perf and yet it doesn't even
try to reduce the number of under/overflow & bounds checks.

That's a lot of code that will never be run and that also introduces
unncessary branches which hurt perf.

Modification:

Remove a bunch of low hanging fruit checks.

Result:

Faster (and less) code.

### CODE REVIEW

**Comment by weissi** [comment]
@swift-nio-bot perf test please

**Comment by weissi** [comment]
@swift-nio-bot perf test please

**Review by Lukasa — APPROVED** [review]
This LGTM, nice patch!

**Comment by Lukasa** [comment]
@swift-nio-bot test perf please

**Review by dnadoba — APPROVED** [review]
LGTM.

**Pull request merged**
