### PR TITLE
[GHA] Benchmark job

### PR DESCRIPTION
**Pull request by FranzBusch**
# Motivation

We need to run our `benchmark-package` based benchmarks on GH action as well. This is another part that we can make reusable for other packages.

# Modification

Add a new `benchmarks-linux` job to the reusable workflow.

# Result

One more CI flow migrated.

### CODE REVIEW

**Comment by FranzBusch** [comment]
@swift-server-bot test this please

**Review by glbrntt — APPROVED** [review]
Looks good but just wondering about the approach here as each job implicitly picks up all Swift versions to run on which isn't that flexible. One example which comes to mind is a new package starting with support only for the latest version of Swift. It seems like the step should be the reusable component (I'm not familiar with GH workflows so don't know how feasible this is) or that each job should take platforms as a parameter.

**Comment by FranzBusch** [comment]
> Looks good but just wondering about the approach here as each job implicitly picks up all Swift versions to run on which isn't that flexible. One example which comes to mind is a new package starting with support only for the latest version of Swift. It seems like the step should be the reusable component (I'm not familiar with GH workflows so don't know how feasible this is) or that each job should take platforms as a parameter.

Making the minimum Swift version configurable is on the list. I was thinking about having a general input of minimum version and then skipping both unit and benchmarks depending on that input.

**Comment by glbrntt** [comment]
What about other platforms?

**Comment by FranzBusch** [comment]
@swift-server-bot test this please

**Comment by FranzBusch** [comment]
> What about other platforms?

I think we can use a similar concept. It depends on well toolchain installation is going to work on the macOS runners.

**Comment by FranzBusch** [comment]
@swift-server-bot test this please

**Pull request merged**
