### PR TITLE
SPI(AsyncChannel): Make `NIOAsyncChannel` a struct

### PR DESCRIPTION
**Pull request by FranzBusch**
# Motivation
To reduce allocations when wrapping a channel into a `NIOAsyncChannel` we should make the `NIOAsyncChannel` a struct instead of a class.

# Modification
This PR changes the `NIOAsyncChannel` to a struct.

### CODE REVIEW

**Review by glbrntt — APPROVED** [review]

**Comment by FranzBusch** [comment]
@swift-server-bot test this please

**Comment by FranzBusch** [comment]
API breakage is expected since we change from a `class` to a `struct`. @Lukasa you mind merging this one as well?

**Comment by FranzBusch** [comment]
@swift-server-bot test this please

**Comment by FranzBusch** [comment]
Okay CI is green now and PR updated @Lukasa

**Review by Lukasa — APPROVED** [review]

**Pull request merged**
