### PR TITLE
swift 5 docker support

### PR DESCRIPTION
**Pull request by tomerd**
Motivation: easily build and test swift-nio v1 using swift 5 docker

Modifications: adjust dockerfile and add docker-compose file for ubuntu 18.04, swift 5

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-nio-bot test this please

**Comment by tomerd** [comment]
@weissi per your request, added swift 5 PRBs. looks like the integration tests are failing tho

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Comment by weissi** [comment]
(retested because spurious test error (more than 20% overhead from the syscall wrappers)

**Comment by weissi** [comment]
blocked behind #954

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Pull request merged**
