### PR TITLE
fix new Swift 5 warnings for NIO 1

### PR DESCRIPTION
**Pull request by weissi**
Motivation:

Swift 5 brought a bunch of new warnings for NIO 1.

Modifications:

fix the warnings

Result:

happier compiles

### CODE REVIEW

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Comment by tomerd** [comment]
@swift-nio-bot test this please

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Comment by weissi** [comment]
@FranzBusch we can take this one now but you'd need to run `scripts/generate_linux_tests.rb` and record the changes, that should get the CI happy

**Pull request merged**
