### PR TITLE
Added some unit tests to MarkedCircularBuffer

### PR DESCRIPTION
**Pull request by MarkusJais**
Motivation:

MarkedCircularBuffer was missing unit tests for some methods and
public attributes

Modifications:

Added several unit tests

Result:

Now MarkedCircularBuffer has better test coverage

### CODE REVIEW

**Comment by normanmaurer** [comment]
@MarkusJais can you please fix the typo  (MarkuedCircularBuffer) in the commit message . Thanks!

**Comment by MarkusJais** [comment]
I've run the Linux script again. There were no real changes, just indentation of a bracket in the Tests/NIOTests/MarkedCircularBufferTests+XCTest.swift file.
I hope this helps.

**Comment by normanmaurer** [comment]
@swift-nio-bot test this please

**Comment by weissi** [comment]
hit #563 too

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Comment by normanmaurer** [comment]
@swift-nio-bot test this please

**Comment by normanmaurer** [comment]
@MarkusJais thanks!

**Pull request merged**
