### PR TITLE
fix doc generation script

### PR DESCRIPTION
**Pull request by tomerd**
motivation: generate docs

changes: use a more robust path to source-kitten

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Review by Lukasa — APPROVED** [review]

**Pull request merged**
