### PR TITLE
Simplify ChannelHandlerContext

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

We can simplify the init method of ChannelHandlerContext and replace one let by a computed property.

Modifications:

Remove some if let statements that we not need and use computed property.

Result:

Simpler code and need one less variable per ChannelHandlerContext.

### CODE REVIEW

**Comment by vlm** [comment]
Did you measure the effect? The performance impact is not obvious to me. The pipeline code requires one more cache line access compared to the previous code.

**Comment by normanmaurer** [comment]
@vlm honestly I did not but I think we have much more to worry about then one cache line access. I would "trade" the access to save memory here honestly. @weissi @Lukasa WDYT ?

**Comment by Lukasa** [comment]
My instinct is that the cache line access is not costly as it will frequently be paged in when doing pipeline ops. However, it may well be worth benchmarking, as the memory savings here add up to many pages in high-utilisation applications.

**Comment by normanmaurer** [comment]
@Lukasa it may also worth to note that the EventLoop will only be accessed when we create a new promise or when we do the assert.

**Comment by normanmaurer** [comment]
@swift-nio-bot test this please

**Comment by normanmaurer** [comment]
@swift-nio-bot test this please

**Comment by weissi** [comment]
I'd agree with @Lukasa and @normanmaurer that my instinct is that is doesn't make a big difference. I'd propose the following: Let's just run a very simple benchmark echo/http and see if the numbers look the same. If they do let's get this merged, if they don't let's go back to the drawing board. I realise that this sort of simple benchmark isn't quite appropriate to test the effects of that very change but I'd think it's good enough for now.

**Comment by normanmaurer** [comment]
I did run some benchmarks and the performance looks the same...

**Pull request merged**
