### PR TITLE
Avoid implicit conversion.

### PR DESCRIPTION
**Pull request by Lukasa**
Motivation:

We were inadvertently doing an implicit integer conversion from
ssize_t to unsigned int in our sendmmsg shim. This can sometimes
generate warnings. The conversion itself is safe.

Modifications:

Make the conversion explicit.

Result:

No warnings.

### CODE REVIEW

**Comment by Lukasa** [comment]
Another intermittent test failure in the integration test.

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by weissi** [comment]
@Lukasa the reset during TCP one, right?

**Comment by weissi** [comment]
ie. #563

**Comment by weissi** [comment]
@Lukasa sorry, saw you commented in #563

**Comment by Lukasa** [comment]
Backporting to 1.9.1.

**Pull request merged**
