### PR TITLE
Add example links

### PR DESCRIPTION
**Pull request by therealbnut**
Adds links to the example repositories to the README.

### Motivation:

Currently the README does not have any quickly consumable examples.

### Modifications:

Inserts an example section into the README

### Result:

More visibility of example usage.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@swift-nio-bot test this please

**Comment by tomerd** [comment]
thank you for the contribution, can you please move this section after the “Documentation” one

**Comment by therealbnut** [comment]
@tomerd done in https://github.com/apple/swift-nio/pull/64/commits/f277d82086445cb0d229a23a82600181334312b9, although if in future if an example is inlined in the README it would be good to have it near the top of the file.

**Comment by therealbnut** [comment]
Context/source for this PR https://twitter.com/normanmaurer/status/969412570481246208

**Comment by therealbnut** [comment]
@normanmaurer @weissi @tomerd thanks for the speedy review 🎉

Someone else will have to merge for me, I don’t have permissions.

**Comment by normanmaurer** [comment]
@therealbnut done... thanks!

**Pull request merged**
