### PR TITLE
Turn off Jekyll for GitHub Pages

### PR DESCRIPTION
**Pull request by Dev1an**
Makes the documentation pages whose filename start with an `_` accessible for everyone.

### Motivation:

At this moment it is not possible to read the documentation of classes, protocols, etc. whose name start with an underscore. For example: when you
- go to the [official API documentation](https://apple.github.io/swift-nio/docs/current/NIO/index.html)
- click on `_ChannelInboundHandler`

→ You get a **File not found** error.

This is caused by the way GitHub parses the gh-pages branch. More specifically how it interprets files that start with an underscore. More information about this behaviour can be found at [GitHub-Pages help](https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/)

### Modifications:

Changed the documentation generator script so that it adds a file named `.nojekyll` (as explained [here](https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/)) when it is executed on a CI machine that uploads the documentation to the gh-pages branch.

I think @tomerd wrote most of this docs generation script, so maybe he can have a look at this and check whether I modified his script correctly?

### Result:

When you visit the documentation for `_ChannelInboundHandler`, the browser shows the documentation instead of the **File not found** error

### CODE REVIEW

**Comment by Lukasa** [comment]
Yup, @tomerd did the majority of this work so I'm going to tag him in. Thanks for the patch! :sparkles:

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by normanmaurer** [comment]
LGTM as well.

**Comment by weissi** [comment]
thanks @Dev1an , that's great!

**Comment by tomerd** [comment]
thank you @dev1an lgtm can you please rebase

@swift-nio-bot test this please

**Comment by Dev1an** [comment]
@tomerd haha, I had no idea how to undo @weissi 's merge, so I changed the name of my initial branch (to no-jekyll-merge) and suddenly this pull request is closed...

Anyway, I rebased my branch: [no-jekyll](https://github.com/Dev1an/swift-nio/tree/no-jekyll) onto the master. What do I do now? Do I need to add another pull request or can you reopen this PR?

**Comment by weissi** [comment]
@Dev1an After a rebase locally, you have a new version of your branch locally. Then you can just force push it to the branch on GitHub and everything should manually update. So basically

    git push -f name-of-your-github-remote no-jekyll

would override my changes.

**Comment by Dev1an** [comment]
Aha, I didn't know there was something like a force push. Thanks for the clarification @weissi

**Comment by weissi** [comment]
@Dev1an welcome. Use it with care though :)

**Pull request closed without merging**
