### PR TITLE
issue-1036: Fix for dates on Linux test generation script.

### PR DESCRIPTION
**Pull request by agnosticdev**
Fix for dates on Linux test generation script.

### Motivation:

Fix for #1036 to add a date or date range for the header.
These dates are derived from the git log on the file.

### Modifications:

Parsing method to extract the date or date range from the git log
of the file.  This was added to generate_linux_tests.

### Result:

Dynamic date or date range added to the file header.

### CODE REVIEW

**Comment by Lukasa** [comment]
@swift-nio-bot add to allowlist

**Review by Lukasa — CHANGES_REQUESTED** [review]
Great, this broadly seems like it works! Can you apply the changes to the test files and push that up? It should get the CI passing.

**Comment by agnosticdev** [comment]
No problem. Just added the auto-generated files.

**Comment by Lukasa** [comment]
Heh, naturally, this update has forced the each of the test files to themselves need a new update, as they were now revised in 2021. :wink:

**Comment by agnosticdev** [comment]
> Heh, naturally, this update has forced the each of the test files to themselves need a new update, as they were now revised in 2021. 😉

Great point.  Committing these files will pretty much make sure all of them have a `nnnn-2021` on them now. Thoughts on that?

Also, it looks like he `soundness` check failed with a possible `ssh-agent` failure?  Any action item for me there?

**Comment by Lukasa** [comment]
Only the ones whose dates were originally wrong will now have -2021 on them, which is fine: they were all updated in 2021. No action on the ssh-agent issue, I think we'll be fine.

**Comment by Lukasa** [comment]
Just a reminder to re-run your script to get the dates to all be -2021 as needed.

**Review by Davidde94 — APPROVED** [review]
Looks good once the update files are here!

**Comment by agnosticdev** [comment]
I regenerate the dates on the `XCTests` using the updated script and push the files up on the last commit.

**Review by Lukasa — APPROVED** [review]

**Pull request merged**
