### PR TITLE
Fix RepeatedTask scheduling logic to run on the correct EL

### PR DESCRIPTION
**Pull request by gmilos**
Fixes`RepeatedTask` scheduling bug, exhibited if the task returns ELF bound to another ELG than the task itself.

### Motivation:

Fixes: https://github.com/apple/swift-nio/issues/1334

### Modifications:

ELF hops on the correct EL before executing.

### Result:

Fixes precondition failure, caused by being on the wrong ELG.

### CODE REVIEW

**Comment by weissi** [comment]
@swift-nio-bot add to whitelist

**Comment by Lukasa** [comment]
@gmilos Looks like you didn't run the test generation script

**Comment by gmilos** [comment]
The 5.1 test failed due to timeout:
```
19:13:39 Running test 'test_01_allocation_counts.sh'... Build timed out (after 10 minutes). Marking the build as failed.
19:23:39 $ ssh-agent -k
```
Is that common? Rerun and hope for the best?

**Comment by Lukasa** [comment]
Yeah, it's a known issue with the allocation counter tests. @PeterAdams-A is investigating.

**Comment by PeterAdams-A** [comment]
@swift-nio-bot test this please

**Pull request merged**
