### PR TITLE
Fix memory binding.

### PR DESCRIPTION
**Pull request by ser-0xff**
Fix memory binding.

### Motivation:

According to the documentation the 'capacity' argument represent the amount of memory counted as instances of T. Number of bytes allocated for the memory block does not always the same value as a number of instances.

### Modifications:

bindMemory(:, capacity:) called with capacity equal to number of items in the vector instead of size of vector in bytes.

### Result:

Proper memory binding.

### CODE REVIEW

**Review by Lukasa — APPROVED** [review]

**Comment by Lukasa** [comment]
@swift-server-bot test this please

**Comment by Lukasa** [comment]
This LGTM but needs to be rebased onto main.

**Comment by Lukasa** [comment]
This still needs to be rebased onto main, and sadly I can't do it as you haven't made the branch editable by admins.

**Comment by ser-0xff** [comment]
I synced the branch with swift-nio/main and asked to give you rights resync it.

**Comment by Lukasa** [comment]
@swift-server-bot test this please

**Review by Lukasa — APPROVED** [review]

**Pull request merged**
