### PR TITLE
test pr to see if the API breakage checker works

### PR DESCRIPTION
**Pull request by tomerd**
deliberately breaking the public API to see if the tooling works.

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-nio-bot test api please

**Comment by tomerd** [comment]
@swift-nio-bot test api please

**Comment by tomerd** [comment]
@swift-nio-bot test this please

**Comment by tomerd** [comment]
@swift-nio-bot test this please

**Comment by tomerd** [comment]
@swift-nio-bot test this please

**Comment by weissi** [comment]
@tomer you're the best. This is awesome!!

```
03:15:42 Checking _NIO1APIShims.json... OK
03:15:42 Checking NIOConcurrencyHelpers.json... OK
03:15:42 Checking NIOFoundationCompat.json... OK
03:15:42 Checking NIOHTTP1.json... OK
03:15:42 Checking NIO.json... OK
03:15:43 Checking NIOTestUtils.json... OK
03:15:43 Checking NIOTLS.json... OK
03:15:43 Checking NIOWebSocket.json... ERROR
03:15:43 ==============================
03:15:43 ERROR: public API change in NIOWebSocket.json
03:15:43 ==============================
03:15:43 
03:15:43 /* Generic Signature Changes */
03:15:43 
03:15:43 /* RawRepresentable Changes */
03:15:43 
03:15:43 /* Removed Decls */
03:15:43 EnumElement WebSocketErrorCode.unexpectedServerError has been removed
03:15:43 
03:15:43 /* Moved Decls */
03:15:43 
03:15:43 /* Renamed Decls */
03:15:43 
03:15:43 /* Type Changes */
03:15:43 
03:15:43 /* Decl Attribute changes */
03:15:43 
03:15:43 /* Fixed-layout Type Changes */
03:15:43 
03:15:43 /* Protocol Conformance Change */
03:15:43 
03:15:43 /* Protocol Requirement Change */
03:15:43 
03:15:43 /* Class Inheritance Change */
03:15:43 done
```

it totally noticed the API breakage :)

Also CC @xwu, this is really cool

**Pull request closed without merging**
