### PR TITLE
Adopt `Sendable` for `Channel`

### PR DESCRIPTION
**Pull request by dnadoba**
Incremental `Sendable` adoption

### CODE REVIEW

**Comment by Davidde94** [comment]
I don't think we want anything to do with `Channel` to be `Sendable` - everything should happen on the event loop.

**Comment by glbrntt** [comment]
> I don't think we want anything to do with `Channel` to be `Sendable` - everything should happen on the event loop.

`Channel`s are thread-safe so this is fine.

**Comment by Davidde94** [comment]
cc @Lukasa

**Comment by Davidde94** [comment]
Also wouldn't this be a breaking change as it will require any implementation of `Channel` to conform?

**Review by Lukasa — APPROVED** [review]
`Channel`s are very much required to be `Sendable`: they are deliberately intended to be manipulated from multiple threads.

As to the fact that this will require conformances, thanks to the `@preconcurrency` annotation it will only require conformances once users start adopting concurrency. Anyone importing NIO who has _not_ adopted concurrency will not need to add a conformance.

**Comment by Lukasa** [comment]
API breakage checker is mad about the new protocol.

**Review by fabianfett — APPROVED** [review]

**Pull request merged**
