### PR TITLE
EventLoopFuture/Promise: only Sendable if Value is Sendable

### PR DESCRIPTION
**Pull request by weissi**
### Motivation:

`EventLoopFuture/Promise` are (incorrectly) marked as unconditionally `Sendable`. But this allows to send non-`Sendable` values which isn't right.

### Modifications:

Mark `EventLoopFuture/Promise` as conditionally `Sendable` if `Value` is `Sendable`.

This is technically API breaking but given the nature of the `Sendable` protocol should only result in warnings in the very most cases. The NIO release tools will assess compatibility.

### Result:

- More correctness
- More warnings for users (sorry NIO users)

### CODE REVIEW

**Review by Lukasa — CHANGES_REQUESTED** [review]
I'm remarkably nervous about merging this, but it must not merge until immediately after a release. We need some time for the release validation to bake. Marking "request changes" to block an accidental merge.

**Comment by weissi** [comment]
> I'm remarkably nervous about merging this, but it must not merge until immediately after a release. We need some time for the release validation to bake. Marking "request changes" to block an accidental merge.

Good idea. Yes, I'd suggest to make a NIO minor release _JUST_ for this PR :). If something goes side-ways we can "repair" it by undoing it in a follow-up patch version (think in SemVer this is allowed if something was done accidentally).

**Comment by ktoso** [comment]
Overall it’s a good idea, but I support the careful rollout 👍

**Comment by weissi** [comment]
> Also very nervous about this, especially about Swift 5.6/5.7. But it is the right thing to do.

I mean we _could_ (not saying we necessarily) should `#if compiler(>5.9)` this whole thing and then nothing changes until 5.9 is released :P.

**Comment by Lukasa** [comment]
Sadly that's still a source break :wink:

**Comment by weissi** [comment]
> Sadly that's still a source break 😉

No disagreement here

**Review by Lukasa — APPROVED** [review]
OK, I think we can land this and see what happens.

**Comment by Lukasa** [comment]
FYI @simonjbeaumont who is monitoring the release tools at this time.

**Pull request merged**
