### PR TITLE
make ByteBuffer._Storage.fullSlice a computed property

### PR DESCRIPTION
**Pull request by weissi**
Motivation:

ByteBuffer._Storage.fullSlice can always be trivially computed, so it
should be.

Modifications:

make ByteBuffer._Storage.fullSlice computed

Result:

saved almost 56 bits per ByteBuffer 😂

### CODE REVIEW

**Comment by Lukasa** [comment]
@weissi Looks like an integration test failed here, want to take a quick look?

**Comment by weissi** [comment]
@Lukasa thanks filed as #563 will investigate shortly.

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Comment by weissi** [comment]
hit a slow node:

```
14:47:25 Fatal error: Posix wrapper adds more than 20% overhead (with wrapper: 0.751054048538208, without: 0.594343900680542: file /tmp/.swift-nio-syscall-wrappers-sh-test_71I49G/syscallwrapper/Sources/syscallwrapper/SystemCallWrapperHelpers.swift, line 124
```

**Pull request merged**
