### PR TITLE
add an Xcode workspace setting the file header automatically

### PR DESCRIPTION
**Pull request by weissi**
Motivation:

We have a requirement to have the right file headers containing
licensing information. Unfortunately that was an all manual process but
by adding an `xcworkspace` which references the `xcodeproj` that SwiftPM
can generate, Xcode will automatically put the right file header there.

Modifications:

Added `swift-nio.xcworkspace` which references `swift-nio.xcodeproj`
(which must be generated by SwiftPM using `swift package generate-xcodeproj`).

Result:

File headers should automatically be right when a new file is created in
Xcode.

### CODE REVIEW

**Comment by normanmaurer** [comment]
Nice one 👍

**Comment by tomerd** [comment]
personally i am not a fan of adding IDE settings to the source tree, and prefer to make that a function of the build/toolchain. that said, since xcode is pretty much the only game in town atm it’s okay i guess?

**Comment by normanmaurer** [comment]
@tomerd I think its better then nothing :)

**Comment by weissi** [comment]
@tomerd I tried to make an `xcconfig` which can be passed to `swift package generate-xcodeproj --xcconfig-overrides` plus a script which passes the right arguments. Unfortunately, it seems that this is only possible using an `xcworkspace` which isn't generated by SwiftPM. So whilst I agree with you, I also agree with @normanmaurer that it's better than nothing :|

**Comment by tomerd** [comment]
yup yup, any chance we stash it behind Xcode directory or something like that? if no, lets just move forward and address later. paging @ddunbar @aciidb0mb3r

**Comment by weissi** [comment]
@tomerd thought about putting it in `dev/` but the problem is that it should be discoverable. And if you just type `swift package generate-xcodeproj` then the Xcode project gets generated in the top-level dir. So I wanted to have the `.xcworkspace` next to it in order for people to see it and open that instead of the project directly...

**Comment by ianpartridge** [comment]
There is a problem with this PR in my view...

If we merge it then people who `git clone https://github.com/apple/swift-nio` will see the Xcode workspace, do `open swift-nio.xcworkspace` (not unreasonably), and then find that the workspace is broken because `swift-nio.xcodeproj` doesn't exist.  Which is not a great experience for the first-time contributor.

**Comment by weissi** [comment]
@ianpartridge that's definitely true but I don't know how we could improve on that. Xcode will show the `xcodeproj` as missing which will hopefully make people create it using `swift package generate-xcodeproj`. But you're right, it might not be obvious to a first time contributor :|. @ddunbar / @aciidb0mb3r what do you recommend here?

**Comment by aciidb0mb3r** [comment]
You can check if the project is present in a shell script phase and then warn or error. It will be required to re-open the workspace after generating the project. Not the best UX, but I don't have a better solution either.

**Comment by weissi** [comment]
@ianpartridge what do you think about @aciidb0mb3r ‘s suggestion?

@tomerd @normanmaurer @Lukasa we can also just kill this PR and leave it as is. What do you think?

**Comment by weissi** [comment]
Closing

**Pull request closed without merging**
