### PR TITLE
Reduce selector wakeups.

### PR DESCRIPTION
**Pull request by Lukasa**
Motivation:

Right now all tasks scheduled onto an event loop from a different loop
wake up the underlying selector by writing to an eventfd. This is a
fairly inefficient way to handle things: it incurs a lot of syscall
traffic unnecessarily.

Given that we currently protect the pending tasks queue with a big dumb
lock, we can safely keep track of whether we're going to dequeue this
task. If we are, we don't need to wake the selector.

Modifications:

- Keep track of whether we're de-queueing tasks or not.
- Arrange to wake the selector only once.

Result:

Cheaper task enqueueing on hot loops.

cc @hassila, who will be affected by this patch

### CODE REVIEW

**Comment by Lukasa** [comment]
Re-running: the 5.0 CI is somewhat implying I managed to add allocations, which seems impossible. I'll try again and we'll see.

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Review by glbrntt — APPROVED** [review]
Looks good to me.

**Review by weissi — APPROVED** [review]
Thanks! LGTM (after fixing George's comment)

**Comment by Lukasa** [comment]
Ok, the allocation regression on 5.0 is caused by an optimiser failure. The line that is now allocating is the call to `Selector.whenReady`.


In 5.0 on `main` in `SelectableEventLoop.run` the optimiser generates a call to `function signature specialization <Arg[1] = [Closure Propagated : closure #1 (NIO.SelectorEvent<NIO.NIORegistration>) -> () in closure #2 () throws -> () in NIO.SelectableEventLoop.run() throws -> (), Argument Types : [NIO.SelectableEventLoop]> of generic specialization <NIO.NIORegistration> of NIO.Selector.whenReady0(strategy: NIO.SelectorStrategy, _: (NIO.SelectorEvent<A>) throws -> ()) throws -> ()`. I find it helpful to break names like this down a bit:

- `function signature specialization`
    - `<Arg[1] = [Closure Propagated :`
        - `closure #1 (NIO.SelectorEvent<NIO.NIORegistration>) -> () in`
        - `closure #2 () throws -> () in`
        - `NIO.SelectableEventLoop.run() throws -> ()`
    - `, Argument Types : [NIO.SelectableEventLoop]>`
- `of generic specialization <NIO.NIORegistration>`
- `of NIO.Selector.whenReady0(strategy: NIO.SelectorStrategy, _: (NIO.SelectorEvent<A>) throws -> ()) throws -> ()`

Reading this directly, the optimiser has specialised `NIO.Selector.whenReady0` twice. Firstly it specialized the generic `Selector` type for `NIORegistration` (which we'd expect to see). Then it specialized the function signature to change how `Arg[1]` (the `body` closure) was passed. The specific change is that the closure was propagated: that is, the function was generated with the closure embedded in the function body, instead of being passed in.

The result here is that this optimisation removes the need to heap-allocate for the closure.

Sadly, the extra closure in this code after this change seems to break the optimiser. We now get a call to `generic specialization <NIO.NIORegistration> of NIO.Selector.whenReady0(strategy: NIO.SelectorStrategy, onLoopBegin: () -> (), _: (NIO.SelectorEvent<A>) throws -> ()) throws -> ()`: the generic specialization still applies, but the function signature specialization is gone.

Unfortunately, this causes us to allocate, though interestingly we only allocate for the same closure (now called `closure #2 (NIO.SelectorEvent<NIO.NIORegistration>) -> () in closure #2 () throws -> () in NIO.SelectableEventLoop.run() throws -> ()`). The closure we newly added does not need a heap allocation. This seems to be the result of reabstraction: the closures we call are `partial apply forwarder for closure #1 () -> () in closure #2 () throws -> () in NIO.SelectableEventLoop.run() throws -> ()` and `partial apply forwarder for reabstraction thunk helper from @callee_guaranteed (@guaranteed NIO.SelectorEvent<NIO.NIORegistration>) -> (@error @owned Swift.Error) to @escaping @callee_guaranteed (@in_guaranteed NIO.SelectorEvent<NIO.NIORegistration>) -> (@error @owned Swift.Error)`, indicating that for some reason `closure #2` managed to be reabstracted to `@escaping @callee_guaranteed` from `@callee_guaranteed`. That seems to have forced the heap allocation.

Fixing this is somewhat awkward.

**Comment by weissi** [comment]
let's definitely not care about 5.0

**Comment by hassila** [comment]
Wouldn't it be reasonable to take that hit on 5.0 to get the improvement with syscall reduction for all versions? (nice troubleshooting)

**Comment by weissi** [comment]
> Wouldn't it be reasonable to take that hit on 5.0 to get the improvement with syscall reduction for all versions? (nice troubleshooting)

100%. Let's not care about 5.0, 5.1, 5.2 (and soon also not about 5.3). If somebody wants performance they ought to run the latest available version.

**Comment by Lukasa** [comment]
See #1826

**Comment by weissi** [comment]
@swift-nio-bot test perf please

**Comment by Lukasa** [comment]
Regarding perf, here's what I got by comparing the perf results from the `main` branch:

| name | current | previous | winner | diff |
|--|--|--|--|--|
| write_http_headers | 0.004241572 | 0.004219631 | previous | 0% |
| bytebuffer_write_12MB_short_string_literals | 0.513647566 | 0.525202478 | current | -2% |
| bytebuffer_write_12MB_short_calculated_strings | 0.514879107 | 0.524986757 | current | -1% |
| bytebuffer_write_12MB_medium_string_literals | 0.182124012 | 0.187965405 | current | -3% |
| bytebuffer_write_12MB_medium_calculated_strings | 0.229405174 | 0.228535305 | previous | 0% |
| bytebuffer_write_12MB_large_calculated_strings | 0.204255632 | 0.217854723 | current | -6% |
| bytebuffer_lots_of_rw | 0.56375112 | 0.5697594 | current | -1% |
| bytebuffer_write_http_response_ascii_only_as_string | 0.041572609 | 0.041440377 | previous | 0% |
| bytebuffer_write_http_response_ascii_only_as_staticstring | 0.031846337 | 0.032644366 | current | -2% |
| bytebuffer_write_http_response_some_nonascii_as_string | 0.041459706 | 0.042963408 | current | -3% |
| bytebuffer_write_http_response_some_nonascii_as_staticstring | 0.031514052 | 0.033629605 | current | -6% |
| no-net_http1_10k_reqs_1_conn | 0.14162955 | 0.144655599 | current | -2% |
| http1_10k_reqs_1_conn | 0.621038691 | 0.621144065 | current | 0% |
| http1_10k_reqs_100_conns | 0.626040686 | 0.626548365 | current | 0% |
| future_whenallsucceed_100k_immediately_succeeded_off_loop | 0.09081243 | 0.089873808 | previous | 1% |
| future_whenallsucceed_100k_immediately_succeeded_on_loop | 0.090419233 | 0.089656409 | previous | 0% |
| future_whenallsucceed_100k_deferred_off_loop | 0.366515426 | 0.407651498 | current | -10% |
| future_whenallsucceed_100k_deferred_on_loop | 0.142151743 | 0.138564649 | previous | 2% |
| future_whenallcomplete_100k_immediately_succeeded_off_loop | 0.035409018 | 0.035398623 | previous | 0% |
| future_whenallcomplete_100k_immediately_succeeded_on_loop | 0.036154412 | 0.036256504 | current | 0% |
| future_whenallcomplete_100k_deferred_off_loop | 0.277032303 | 0.306946961 | current | -9% |
| future_whenallcomplete_100k_deferred_on_loop | 0.073358225 | 0.073651886 | current | 0% |
| future_reduce_10k_futures | 0.038224375 | 0.03705496 | previous | 3% |
| future_reduce_into_10k_futures | 0.03658473 | 0.035789139 | previous | 2% |
| channel_pipeline_1m_events | 0.174387376 | 0.175064142 | current | 0% |
| websocket_encode_50b_space_at_front_1m_frames_cow | 0.825297805 | 0.833303569 | current | 0% |
| websocket_encode_50b_space_at_front_1m_frames_cow_masking | 0.092771858 | 0.09333591 | current | 0% |
| websocket_encode_1kb_space_at_front_100k_frames_cow | 0.085487613 | 0.085806439 | current | 0% |
| websocket_encode_50b_no_space_at_front_1m_frames_cow | 0.827969553 | 0.8288855 | current | 0% |
| websocket_encode_1kb_no_space_at_front_100k_frames_cow | 0.085679694 | 0.086035516 | current | 0% |
| websocket_encode_50b_space_at_front_10k_frames | 0.011100694 | 0.011257305 | current | -1% |
| websocket_encode_50b_space_at_front_10k_frames_masking | 0.119885073 | 0.121498991 | current | -1% |
| websocket_encode_1kb_space_at_front_1k_frames | 0.001971608 | 0.002007003 | current | -1% |
| websocket_encode_50b_no_space_at_front_10k_frames | 0.010918528 | 0.010930245 | current | 0% |
| websocket_encode_1kb_no_space_at_front_1k_frames | 0.001969634 | 0.00197205 | current | 0% |
| websocket_decode_125b_100k_frames | 0.144243456 | 0.148299127 | current | -2% |
| websocket_decode_125b_with_a_masking_key_100k_frames | 0.153115008 | 0.155845549 | current | -1% |
| websocket_decode_64kb_100k_frames | 0.151495449 | 0.154466187 | current | -1% |
| websocket_decode_64kb_with_a_masking_key_100k_frames | 0.16074986 | 0.16244525 | current | -1% |
| websocket_decode_64kb_+1_100k_frames | 0.151937578 | 0.153693808 | current | -1% |
| websocket_decode_64kb_+1_with_a_masking_key_100k_frames | 0.159968188 | 0.161163763 | current | 0% |
| circular_buffer_into_byte_buffer_1kb | 0.046944672 | 0.04693662 | previous | 0% |
| circular_buffer_into_byte_buffer_1mb | 0.094043354 | 0.094023675 | previous | 0% |
| byte_buffer_view_iterator_1mb | 0.133912457 | 0.133910545 | previous | 0% |
| byte_to_message_decoder_decode_many_small | 3.4e-08 | 3.0e-08 | previous | 13% |

**Pull request merged**
