### PR TITLE
Just store NIOAny in the pending array.

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

We stored a closure in the pending array which is not really needed. We can just store the NIOAny directly without creating a closure first.

Modifications:

Replace closure with NIOAny

Result:

Less creation of closures.

### CODE REVIEW

**Comment by normanmaurer** [comment]
noticed this while working on http perf stuff.

**Comment by weissi** [comment]
@normanmaurer would you mind seeing what this does to the number of allocations we do? Just run

    IntegrationTests/run-tests.sh -vf test_01_all

and paste those lines that appear close to the end of (a lot of) output:

```
DEBUG: [["remaining_allocations": 7, "total_allocations": 325378], ["remaining_allocations": 0, "total_allocations": 325357], ["remaining_allocations": 0, "total_allocations": 325360], ["remaining_allocations": 0, "total_allocations": 325364], ["remaining_allocations": 0, "total_allocations": 325369], ["remaining_allocations": 0, "total_allocations": 325360], ["remaining_allocations": 0, "total_allocations": 325366], ["remaining_allocations": 0, "total_allocations": 325361], ["remaining_allocations": 0, "total_allocations": 325360], ["remaining_allocations": 0, "total_allocations": 325366]]
1_reqs_1000_conn.remaining_allocations: 0
1_reqs_1000_conn.total_allocations: 1686163
DEBUG: [["remaining_allocations": 0, "total_allocations": 1690497], ["remaining_allocations": 0, "total_allocations": 1690400], ["remaining_allocations": 0, "total_allocations": 1689557], ["remaining_allocations": 0, "total_allocations": 1689876], ["remaining_allocations": 0, "total_allocations": 1689258], ["remaining_allocations": 0, "total_allocations": 1689059], ["remaining_allocations": 0, "total_allocations": 1688610], ["remaining_allocations": 0, "total_allocations": 1688442], ["remaining_allocations": 0, "total_allocations": 1686570], ["remaining_allocations": 0, "total_allocations": 1686163]]
```

the test will also take quite a while to run...

**Comment by normanmaurer** [comment]
Before:

```
1000_reqs_1_conn.total_allocations: 325360
```

With this pr:

```
1000_reqs_1_conn.total_allocations: 315350
```

**Comment by weissi** [comment]
@normanmaurer awesome 👏. That removes 10 allocations _per request_!

**Pull request merged**
