### PR TITLE
atomics+lock: Capitalise filenames

### PR DESCRIPTION
**Pull request by ianpartridge**
Capitalise `Atomics.swift` and `Lock.swift`.

### Motivation:

By convention, Swift filenames are capitalised.

### Modifications:

Capitalise `Atomics.swift` and `Lock.swift`.

### Result:

Swift filenames are capitalised.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@Lukasa @weissi didnt this kind of renaming cause us issues before ?

**Comment by normanmaurer** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
Yup, I formally propose we don't merge this. Changing case like this will break a huge number of currently existing checkouts on case-insensitive filesystems like the one macOS has, so I think we shouldn't do it.

**Comment by ianpartridge** [comment]
So we're stuck with it forever? That seems very unfortunate.

**Comment by weissi** [comment]
We should test whether renaming it from ‘foo’ to ‘Foo-rename’ and then in a new PR/commit from ‘Foo-rename’ to ‘Foo’. That might work. I can test it after my skiing holiday, happy if someone files and issue against me figuring that out.

**Comment by Lukasa** [comment]
@weissi It won't work. Anyone who consumes the patch sequence directly will hit this issue. Similarly, after `git gc` packs that chain the problem comes back up.

@ianpartridge It's not *that* unfortunate, really, is it? I'd describe it as a minor wrinkle. :smile:

**Comment by weissi** [comment]
alright, sad times and thanks @Lukasa

**Pull request closed without merging**
