### PR TITLE
add performance analysis docker-compose setup and script

### PR DESCRIPTION
**Pull request by tomerd**
motivation: prepare to run performance tests in ci

changes:
* add performance-test docker-compose task
* add script that can parse the performance test suite results and compare between two result-sets
* add generic shell docker-compose task

### CODE REVIEW

**Comment by tomerd** [comment]
https://ci.swiftnio.io/job/swift-nio2-performance/plot/

**Comment by tomerd** [comment]
@swift-nio-bot test this please

**Comment by tomerd** [comment]
@weissi @Lukasa this is ready for review

**Comment by weissi** [comment]
@Lukasa / @tomerd happy with this too but Tom asked me to not merge yet yesterday.

**Comment by weissi** [comment]
ok actually, Tom said it's ready for review

**Pull request merged**
