### PR TITLE
Set Swift version to 4.0.3 in Docker configuration

### PR DESCRIPTION
**Pull request by tiagomartinho**
Motivation:
In order to target the latest version of Swift and address this issue https://github.com/apple/swift-nio/issues/83

Modifications:
Set the Swift version to the latest (4.0.3)

Result:
Uniform version of Swift across the Ubuntu Docker image and a passing
test suite on all target platforms

### CODE REVIEW

**Comment by normanmaurer** [comment]
@swift-nio-bot test this please

**Comment by tomerd** [comment]
while i am fine with this change i am not convinced its the root cause of #83 and would like to hold on to this change so we can fix that first. @weissi wdyt?

**Comment by Lukasa** [comment]
So this patch will need to be updated to resolve some conflicts.

**Comment by normanmaurer** [comment]
@tiagomartinho can you please rebase ?

**Comment by tiagomartinho** [comment]
Sorry for the delay @Lukasa  and @normanmaurer (I was visiting Japan after try! Swift).

I rebased the commit!

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by tiagomartinho** [comment]
Thank you!

**Pull request merged**
