### PR TITLE
conform ByteBufferView to Foundation's ContiguousBytes protocol & withContiguousStorageIfAvailable

### PR DESCRIPTION
**Pull request by weissi**
Motivation:

- Foundation has (on master) introduces a ContiguousBytes protocol and we
  should conform to that.
- Sequence has withContiguousStorageIfAvailable and ByteBufferView
  should conform to that too

Modifications:

add conformance

Result:

more compatibility.

### CODE REVIEW

**Comment by weissi** [comment]
@millenomi will [`ContiguousBytes`](https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/ContiguousBytes.swift) actually make it for 5.0?

**Comment by millenomi** [comment]
I see it in https://github.com/apple/swift-corelibs-foundation/commit/7f7edfe220117b8bcfdd36b8a66865792f51e653 which is in swift-5.0-branch. What's the issue?

**Comment by weissi** [comment]
> I see it in [apple/swift-corelibs-foundation@7f7edfe](https://github.com/apple/swift-corelibs-foundation/commit/7f7edfe220117b8bcfdd36b8a66865792f51e653) which is in swift-5.0-branch. What's the issue?

So sorry, I think the problem were my computer operating skills. I checked what I thought was the swift-5.0-branch before but clearly I messed that up.

**Comment by weissi** [comment]
@Lukasa this now finally passes :)

**Comment by weissi** [comment]
ping @Lukasa

**Pull request merged**
