### PR TITLE
Make EventLoopIterator non-optional

### PR DESCRIPTION
**Pull request by FranzBusch**
Return non-optional `EventLoopIterator` from `makeIterator()`

### Motivation:

`makeIterator()` was introduced in 1.9.0 to return an optional `EventLoopIterator` to not require a SemVer major. With 2.0 though we want to make this method return a non-optional.

### Modifications:

Make `makeIterator()` return value non-optional.

### Result:

Every `EventLoopGroup` has a non-optional iterator. This requires a SemVer major.

### CODE REVIEW

**Comment by FranzBusch** [comment]
@Lukasa I just created this to not forget to open up a PR once https://github.com/apple/swift-nio/pull/509 is merged. Can you label this with 2.0 please

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Comment by weissi** [comment]
@swift-nio-bot  test this please

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Comment by weissi** [comment]
@FranzBusch we can take this one now but you'd need to run `scripts/generate_linux_tests.rb` and record the changes, that should get the CI happy

**Comment by weissi** [comment]
ping @FranzBusch

**Comment by weissi** [comment]
closing for #888 where I fix up this PR

**Pull request closed without merging**
