### PR TITLE
Change unncessary functions to variables

### PR DESCRIPTION
**Pull request by BasThomas**
Changes some unncessary functions to computed variables.

### Motivation:

The changed functions do not have any side effects and therefore better convey intent when being a simple computed variable.

### Modifications:

- `func markedElementIndex() -> Int?` to `var markedElementIndex: Int?`
- `func markedElement() -> E?` to `var markedElement: E?`
- `func hasMark() -> Bool` to `var hasMark: Bool`

### Result:

⚠️ **This is a breaking change and needs a major version bump** ⚠️

Changes some unncessary functions to computed variables.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@swift-nio-bot test this please

**Comment by BasThomas** [comment]
That would make sense to me too.

**Comment by BasThomas** [comment]
It just occurred to me that we could already add deprecations for this so that there is a soft migration path to 2.0. Or should we deprecate the functions in favor of computed variables in 2.0?

**Comment by weissi** [comment]
@BasThomas that's a great idea, let's do it. I think we've moved towards that model anyway and I think there's value in having 2.0 as a breaking release that doesn't actually break all that much if people move their code to latest non-deprecated API during 1.x

**Comment by BasThomas** [comment]
I'll open a pr soon :)

**Comment by BasThomas** [comment]
Hm, it seems like it does not like functions and computed variables of the same name... seems like this is not going to work :(

**Comment by weissi** [comment]
@BasThomas oh noe, sad times, thanks for trying!

**Comment by weissi** [comment]
@BasThomas I know you opened this 9 months ago but now we'd be ready to accept this :). Still interested in updating this one?

**Comment by BasThomas** [comment]
Sure!

**Comment by weissi** [comment]
@BasThomas awesome, please ping me when this is rebased

**Comment by BasThomas** [comment]
Opened #695

**Pull request closed without merging**
