### PR TITLE
Add Docker installation instructions to README

### PR DESCRIPTION
**Pull request by tiagomartinho**
Improve README.

### Motivation:

Help developers setting up the project.

### Modifications:

Add Docker installation instructions to README.

### Result:

More complete instructions.

### CODE REVIEW

**Comment by weissi** [comment]
thanks very much for your patch. Would you mind using the git commit template (see [`CONTRIBUTING.md`](https://github.com/apple/swift-nio/blob/master/CONTRIBUTING.md) )? You can find the commit template in [`dev/git.commit.template`](https://github.com/apple/swift-nio/blob/master/dev/git.commit.template)

git can be configured to automatically use it when using `git commit` (without `-m ...`) like this:

    git config commit.template dev/git.commit.template

**Comment by tiagomartinho** [comment]
Thanks for the heads-up @weissi ! Sorry to overlook that guideline.

Does it looks ok now?

**Comment by ianpartridge** [comment]
I'm not sure this is ideal, as it implies that users have to install both Docker and Docker Compose separately.  If you are on macOS and you install [Docker CE for Mac](https://www.docker.com/community-edition#/download) you get both Docker and Docker Compose in one package.

I think it might be best to just point people at the Docker Store?

**Comment by tomerd** [comment]
> I think it might be best to just point people at the Docker Store?

+1

**Comment by tiagomartinho** [comment]
I was following the Docker documentation [here](https://docs.docker.com/compose/gettingstarted/). But I agree, the important thing for me was just to add the missing requirement 😄 .

Should I then point to [Install Docker](https://docs.docker.com/install/)?

**Comment by ianpartridge** [comment]
I think https://www.docker.com/community-edition/ might be the best link, but Docker do unfortunately have a habit of changing their URLs frequently...

**Comment by tiagomartinho** [comment]
Done!

**Comment by tomerd** [comment]
@tiagomartinho how about rephrasing this sections so it reads betters:

```
Alternatively, you may want to develop or test with `docker-compose`.

First make sure you have [Docker](https://www.docker.com/community-edition) installed, next `cd docker` and run the following commands:
```

**Comment by normanmaurer** [comment]
+1 to @tomerd s suggestion... @tiagomartinho please address the comment and let us know one done.

**Comment by tiagomartinho** [comment]
Makes sense!

I've changed the documentation.

**Comment by normanmaurer** [comment]
@swift-nio-bot test this please

**Comment by normanmaurer** [comment]
@tiagomartinho thanks a lot

**Pull request merged**
