### PR TITLE
Add first(name:) to HTTPHeaders

### PR DESCRIPTION
**Pull request by glbrntt**
Motivation:

In some cases you only expect (or care about) a single value for a
header. However, getting this value without allocating an array or
traversing the whole array requres using first(where:) provided by
Sequence. This is not very ergonomic as it requires users to do the
case-insensitive comparison and then exctact the value from the
HTTPHeaders. Additionally, users cannot use NIO's case insensitive
ASCII comparison.

Modifications:

- Provide a first(name:) method on HTTPHeaders which returns the value
  from the first header whose name is a case insentive match of the
  subscript parameter.

Result:

It's easier to get the first value from HTTPHeaders matching a given
name.

### CODE REVIEW

**Comment by glbrntt** [comment]
See also: https://github.com/apple/swift-nio-http2/pull/178

**Comment by Lukasa** [comment]
Huh, segfault in the tests. That's interesting.

**Comment by glbrntt** [comment]
> Huh, segfault in the tests. That's interesting.

Yup https://github.com/apple/swift-nio/issues/1283 -- running it in a loop with lldb, let's see what happens!

**Comment by glbrntt** [comment]
@swift-nio-bot test this please

**Pull request merged**
