### PR TITLE
docker cleanup

### PR DESCRIPTION
**Pull request by tomerd**
Motivation:

repository currently contains two seperate docker definitions that are confusing to users

Modifications:

* remove Dockerfile.xenial so we have a canonical docker file for CI and developer testing
* point docker compose to canonical docker file
* define docker compose services for unit and integration tests. and make "test" service run both
* update readme

Result:

users are less confused about docker setup

### CODE REVIEW

**Comment by Lukasa** [comment]
Why do we need to remove `Dockerfile.xenial`?

**Comment by tomerd** [comment]
@lukasa to make docker compose based testing identical to our CI. there is an argument to be made to add tests for both versions, but until we do i prefer to avoid the confusion this can (and did) cause

**Comment by normanmaurer** [comment]
@tomerd @Lukasa I am fine with the removal as long as we can test everything with 14.04 without any problems :)

**Comment by tomerd** [comment]
yup, that’s what we use in CI

**Comment by normanmaurer** [comment]
@tomerd please rebase and merge.

**Pull request merged**
