### PR TITLE
add NIOFoundationCompat lib to package products

### LINKED ISSUE #54: publicize `NIOFoundationCompat`
Is there a reason this package was not added to the products array in the package manifest?

If that's just an oversight, I'm happy to submit a PR. :)

### PR DESCRIPTION
**Pull request by tanner0101**
Fixes #54

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-nio-bot test this please

**Comment by normanmaurer** [comment]
@swift-nio-bot test this please

**Comment by normanmaurer** [comment]
@swift-nio-bot test this please... this is not related and we have an outstanding pr for the flaky test.

**Comment by normanmaurer** [comment]
@tanner0101 thanks so much!

**Pull request merged**
