### PR TITLE
Update EventLoop.swift typo

### PR DESCRIPTION
**Pull request by Andrewangeta**
Updated the code comment to explain the correct type of `Future` result.
### Motivation:

This is done because when using Xcode and `option + Click` on a function you get a help overview inline to see more information and the messaging was incorrect. This helps developers in the future who want to rely on docs via Xcode.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@Andrewangeta can you please amend the commit message to include what you changed and why ?

**Comment by normanmaurer** [comment]
@swift-nio-bot test this please

**Comment by weissi** [comment]
ping @Andrewangeta . Thanks for your patch, that's great! Mind changing the actual commit message (not just the PR) to match our commit template (see [here](https://github.com/apple/swift-nio/blob/master/CONTRIBUTING.md#writing-a-patch) on how to set up git to do that automatically)

**Comment by normanmaurer** [comment]
@swift-nio-bot test this please

**Pull request merged**
