### PR TITLE
Implement BBV custom contains function to improve performance.

### PR DESCRIPTION
**Pull request by SeJV**
Implement BBV custom contains function to improve performance(#2042).

### Motivation:

This is the implementation for `_customContainsEquatableElement` for increased performance on calling `buffer.readableBytesView.contains(...)` (detailed in #1385).

### Modifications:

Added methods to `ByteBufferView`:
- `_customContainsEquatableElement`

### Result:

`contains()` behaves as before.
Performance is improved.

### CODE REVIEW

**Comment by glbrntt** [comment]
@swift-nio-bot test perf please

**Comment by glbrntt** [comment]
@swift-nio-bot test perf please

**Comment by glbrntt** [comment]
-39%, nice!

byte_buffer_view_contains_12mb | 0.207599396 | 0.345116152 | current | -39%
-- | -- | -- | -- | --

**Comment by glbrntt** [comment]
@swift-nio-bot test this please

**Review by glbrntt — APPROVED** [review]
Awesome, thanks @SeJV!

**Review by fabianfett — APPROVED** [review]
Very cool, thank you!

**Pull request merged**
