### PR TITLE
Made the extern to const in CNIODarwin

### PR DESCRIPTION
**Pull request by BastianInuk**
Externs in CNIODarwin are now const
### Motivation:

Externs should be immutable as per #1867.

### Modifications:

Externs in CNIODarwin got added the const keyword.

### Result:

Externs are now immutable

### CODE REVIEW

**Comment by Lukasa** [comment]
@swift-nio-bot add to allowlist

**Review by Davidde94 — APPROVED** [review]

**Comment by Lukasa** [comment]
I have unlinked #1867 because this only _partially_ fixes that issue.

**Review by Lukasa — APPROVED** [review]

**Comment by BastianInuk** [comment]
I don't have a linux install at hand, so I can't swiftly also run tests on that 😅

**Comment by Davidde94** [comment]
@BastianInuk if you install docker and `cd` into the repo then you can use this docker command:

```
docker run --rm -it -v "$PWD":"$PWD" -w "$PWD" swift:5.0 swift test
```

**Pull request merged**
