### PR TITLE
Remove `@unchecked Sendable` conformance from `ChannelOptions.Storage`

### PR DESCRIPTION
**Pull request by FranzBusch**
# Motivation
We currently have an unchecked `Sendable` conformance on `ChannelOptions.Storage` which is not necessary and in fact we are missing a proper `Sendable` requirement on the `ChannelOption.Value` protocol right now.

# Modification
This PR adds the `Sendable` requirement on the `ChannelOption.Value` and replaces the unchecked conformance on the storage with a regular one.

# Result
No more `Sendable` warnings in strict concurrency mode inside `ChannelOptions`.

### CODE REVIEW

**Review by Lukasa — APPROVED** [review]

**Comment by FranzBusch** [comment]
Breaking change is a false positive:

> 💔 API breakage: protocol ChannelOption has generic signature change from <Self : NIOCore._NIOPreconcurrencySendable, Self : Swift.Equatable> to <Self : NIOCore._NIOPreconcurrencySendable, Self : Swift.Equatable, Self.Value : Swift.Sendable>

**Comment by FranzBusch** [comment]
@swift-server-bot test this please

**Comment by FranzBusch** [comment]
@swift-server-bot test this please

**Comment by FranzBusch** [comment]
The breaking change is expected as above. `Sendable` is only producing warnings before Swift 6 mode. The nightly CI is running into a compiler crash.

**Pull request merged**
