### PR TITLE
Add http-parser license and authors

### PR DESCRIPTION
**Pull request by helje5**
### Motivation:

Quote ([LICENSE-MIT](https://github.com/nodejs/http-parser/blob/master/LICENSE-MIT)):

> The above copyright notice and this permission notice shall be included in
> all copies or substantial portions of the Software.

Just linking is not enough, I think. You have the better lawyers, but it would be the proper thing to do in any case.

### Modifications:

Added the http-parser license.
Added the AUTHORS file. Not required by the license, but again the right thing to do.

### Result:

Proper license inclusion for http-parser.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@helje5 dont we actually already doing this here? :

https://github.com/apple/swift-nio/blob/master/NOTICE.txt#L47

and here:
https://github.com/apple/swift-nio/blob/master/Sources/CNIOHTTPParser/c_nio_http_parser.c#L4

**Comment by normanmaurer** [comment]
I think including the authors is really not needed.

**Comment by normanmaurer** [comment]
@swift-nio-bot please test

**Comment by normanmaurer** [comment]
@swift-nio-bot test this please

**Comment by helje5** [comment]
Well, the NOTICE is IMO definitely not an inclusion as required by the license. But yes, the one in the source itself is fine.

As I said, you don't have to include the AUTHORS, but I think it is not considered nice to leave it out.

In the end: What do you loose by not including those files (and maybe even the README from upstream). 3 files which are not included in the build and 4KB of data? 2ms when cloning the repo?
I would just add the stuff and leave them in as proper credentials. (and eventually replace the http_parser w/ something own ;-) )

**Comment by normanmaurer** [comment]
@Lukasa @weissi thoughts ?

**Comment by weissi** [comment]
@normanmaurer I thought that what we had so far contains everything that's needed but IANAL. I think we should delegate the question if we're currently missing anything to the lawyers.

**Comment by helje5** [comment]
> I thought that what we had so far contains everything that's needed
Yes, it looks like you have everything you *need* (LICENSE also embedded directly in the source, I missed that).
Now you hopefully manage to take the next step and be a nice open source citizen ;-)

**Comment by tanner0101** [comment]
> Now you hopefully manage to take the next step and be a nice open source citizen

Apple lawyers have already poured over every inch of this codebase and subsequently approved it. I don't think it's a good idea for us developers to make any changes to licensing after that.

**Comment by weissi** [comment]
@normanmaurer ping, what should we do here?

**Comment by normanmaurer** [comment]
IMHO we should just close it.

**Comment by helje5** [comment]
IMO you should just do the right thing. Would you like to see your own CONTRIBUTORS.TXT being dropped when someone clones your repro? Most certainly not! If you close this it sends a very specific sign and would make me very unhappy. 😔

**Comment by weissi** [comment]
@helje5 if someone takes NIO and integrates it into their project I would expect them to drop our contributors file but mention that they use NIO. That’s what we did too. We could add to the contributors file that it of course contains contributions from countless other people.

**Comment by weissi** [comment]
@helje5 I don't think an AUTHORS file is meant to be used like that. From what I can tell, NodeJS itself does it just as we do (except that we're still lacking an automatic update script which we should fix):

https://github.com/nodejs/node/blob/master/tools/update-authors.sh

So they wouldn't mention http_parser and on top of that they pull in all of [this](https://github.com/nodejs/node/tree/master/deps) and don't mention it in their AUTHORS file. 

IMHO the authors file is meant for authors that worked on the project you navigated to. And pretty much everybody has dependencies and it'd be a long list if you mention them all. We mention (in NOTICE) that we pull in FreeBSD's SHA1 implementation, http_parser and a few other things, and I guess that makes it obvious that their authors have contributed transitively to NIO too, no?

Do you have a good example for a project that pulls all transitive authors in automatically?

**Comment by helje5** [comment]
> all transitive authors in automatically

I think all this is pretty clear and obvious, but all I ask for is preserving license/author files within the cloned upstream directory. (If you copied the SHA1 sources, I would also place the related documents alongside it, yes).

The more credits you give, they happier I would personally be :-) But I really wouldn't expect you to do unreasonable amounts of extra work, but just preserving the upstream setup and not (unnecessarily!) drop anything along the copying.

> I don't think an AUTHORS file is meant to be used like that

AUTHORS files exist like forever. They are the counterpart to old-school ChangeLog files and are here for exactly this scenario. You pull the sources out of their some repository and put them somewhere else. Nowadays this is a little less common because w/ GitHub the upstream repositories are more stable, direct forking is available and pro-active removals like that are clearly visible in forks (which is why no one would ever dare to do that). Yet sometimes people still directly pull in small projects like http_parser or Expat, this is what ChangeLog/AUTHORs are good for.

BTW: For this particular package the cleanest approach would have been: fork the upstream, enhance w/ the SPM setup. Then import that package into NIO via SPM.


Anyways, I'm tired of the discussion - I find it pretty ridiculous, but as mentioned: your project, your choice. I still hope you do the right thing, but I'm not overly convinced ;-)

**Comment by weissi** [comment]
@helje5 ah, sorry I think I misunderstood you. I'd be up for copying their `AUTHORS` into the same directory as `http_parser.c`. That makes sense to me. I thought you meant merging all their authors into our CONTRIBUTORS file.

**Comment by weissi** [comment]
@helje5 sorry, I re-read your PR and it does also does add their AUTHORS into the directory that contains the 3rd party dependency. For some reason I never saw that and assumed that you argued for adding all the transitive authors to our CONTRIBUTORS file which I don't think is great.

If you modify the [download & patch script](https://github.com/apple/swift-nio/blob/master/Sources/CNIOHTTPParser/update_and_patch_http_parser.sh) to pull those files in, I'd be happy taking this change.

**Comment by Lukasa** [comment]
No objection from me.

**Comment by helje5** [comment]
I modified the script, but couldn't really change it. Where do you get `gsed` from? Installed from source tarball (brew doesn't know about it)

**Comment by weissi** [comment]
@helje5 we can't use the upstream repo as we need to rename the symbols (`c_nio_` prefix) as otherwise you'll get a linker error whenever someone else links http parser. I know this is silly but C doesn't do namespacing and we had too many problems where we defined C symbols that someone else defined as well that we decided to namespace them all. Sad but very effective :).

`gsed` is from `brew install gnu-sed`

**Comment by helje5** [comment]
OK, I fixed the script, it now seems to work fine (also: there is a new version available which adds a new HTTP method SOURCE - surprise, surprise ...)

So if you want, I think you should be able to merge this in.

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Pull request merged**
