### PR TITLE
Get Android constants used by Channel from Bionic instead

### PR DESCRIPTION
**Pull request by buttaface**
### Motivation:

An upcoming pull, apple/swift#35707, moves Android to the same single-header modulemap for Bionic as used on linux, but that doesn't work unless this is changed. This approach works both with the current release toolchain and with that new modulemap.

### Modifications:

Change how these Bionic constants are imported.

### Result:

This repo compiles for Android and the tests pass with both modulemap approaches.

I've been using [an earlier version of this pull to cross-compile this repo on my Android CI](https://github.com/buttaface/swift-android-sdk/blob/main/package-patches/swift-nio-trunk.patch), where [I apply that modulemap pull to the trunk SDK](https://github.com/buttaface/swift-android-sdk/commit/e174127eb23e069c38373f545c52bab8c8615b87#diff-76992bc322b65ab94f299c05ba3cbd8b3ab2e32ebfdde6db5adba70fa9f5a26aR118). Without it, I get the following error with the new modulemap, because of [this definition](https://android.googlesource.com/platform/bionic/+/refs/heads/master/libc/kernel/uapi/linux/if.h#33):
```
swift-nio/Sources/NIOCore/Interfaces.swift:102:31: error: initializer 'init(_:)' requires that 'net_device_flags' conform to 'BinaryInteger'
```

That Bionic pull should be merged into trunk soon, once Daniel, who maintains the community Android CI, approves it. In the meantime, this pull gets this repo working with both approaches.

### CODE REVIEW

**Comment by buttaface** [comment]
I had not tested with old toolchains like 5.2, let's see if this new approach works.

**Comment by buttaface** [comment]
Single failing test on 5.2 looks like a flake: `EventLoopTest.testCancelledScheduledTasksDoNotHoldOnToRunClosure : failed - condition not satisfied in time`.

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
Blocked by #2027.

**Review by Lukasa — APPROVED** [review]

**Pull request merged**
