### PR TITLE
Add assertion helpers for NIOHTTP1TestServer

### PR DESCRIPTION
**Pull request by glbrntt**
Motivation:

Verifying the contents of inbound request parts for `NIOHTTP1TestServer`
can be quite tedious and whenever I use `NIOHTTP1TestServer` in
different projects I find myself writing similar extensions to help
verify the inbound request parts are as expected.

Modifications:

- Add verification methods to `NIOHTTP1TestServer` which checks for the
  expected part and optionally verifies it further in a callback

Result:

It's easier to test with NIOHTTP1TestServer

### CODE REVIEW

**Review by Lukasa — APPROVED** [review]
LGTM, will let @weissi review though.

**Review by weissi — CHANGES_REQUESTED** [review]
I'm requesting changes just because we came up with an improved spelling for the method names (sorry for being a pain with naming). I'm very happy with this change in general.

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by glbrntt** [comment]
@swift-nio-bot test this please

**Review by weissi — APPROVED** [review]
awesome, thanks

**Pull request merged**
