### PR TITLE
Add UnsafeEmbeddedAtomic and use it.

### PR DESCRIPTION
**Pull request by Lukasa**
Motivation:

Many uses of atomics restrict themselves to using atomic variables within
objects that already have reference semantics (i.e. classes) and have
appropriate lifetime management. In this case, the current NIO Atomic
performs an unnecessary heap allocation in order to get itself a reference
count that it can use to free the underlying heap memory.

This is an unnecessary allocation that can often be elided, especially in
situations where many such atomics may be needed. Thus, we should provide
the ability to manually manage the lifetime of the heap-allocated memory for
the atomic, and change some uses of it in our codebase to reduce overhead.

Modifications:

1. Moved most of the code of Atomic to a new struct, UnsafeEmbeddedAtomic.
2. Reimplemented Atomic in terms of UnsafeEmbeddedAtomic.
3. Updated EventLoopFuture to use an UnsafeEmbeddedAtomic for isFulfilled.

Result:

1/3 as many allocations per EventLoopFuture.

### CODE REVIEW

**Comment by Lukasa** [comment]
In addition to this, on @weissi's suggestion I added an allocation test for futures. Before this patch, the allocation result on my Mac was `MAX_ALLOCS_ALLOWED_future_lots_of_callbacks=123004`. After this patch, it was `MAX_ALLOCS_ALLOWED_future_lots_of_callbacks=99004`. This is a reduction of 24k allocations over 1k runs, or 24 allocations per run. This implies we have 24 Futures, which matches my manual reading of the code.

The remaining allocation count is 99k (plus a DC offset of 4 allocations for loops, locks, and other things). This means 99 allocations per run. 48 of those allocations remain for the Futures and atomics, leaving 51 unaccounted-for in this test. I may try @weissi's dtrace memory scripts on this binary to see if I can work out where they are, and whether they can be made to go away.

**Comment by Lukasa** [comment]
Ah, and I can account for the DC offset too. An `EmbeddedEventLoop` (+1), containing a `PriorityQueue` containing a `Heap` containing a `ContiguousArray` (+1). Two `Lock`s (+1 each), one for each call to `wait`. That's 4.

**Comment by Lukasa** [comment]
Further digging reveals that almost all of the other allocations are the result of the cross-module generics cost: allocating boxes for type metadata for all the generic methods on EventLoopFuture. I'm going to quickly investigate what happens if I make all the tested methods on EventLoopFuture inlineable.

**Comment by Lukasa** [comment]
For reasons that I don't fully understand at this time, adding `@_inlineable` and `@_versioned` to most of `EventLoopFuture` actually makes this allocate *more*, not less. I haven't worked out why yet, but I've officially spent more time on trying to figure it out than I can justify. The inlineability seems to be working correctly: I'm seeing specialisations for all of the cases in this test. But somehow, this just leads to more allocation. Weird.

**Comment by tomerd** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
Ok, this is ready for review @normanmaurer @weissi.

**Comment by weissi** [comment]
ok, CI reported `99001` allocations. So in this particular test I'd recommend setting the maximum to `99002` as it should be really stable because it doesn't use multi-threaded event loops

**Comment by normanmaurer** [comment]
Thanks 👍

**Comment by Lukasa** [comment]
Agreed. @tomerd, can we set another CI environment variable? We need `MAX_ALLOCS_ALLOWED_future_lots_of_callbacks=99100` set, please. :grin:

**Comment by tomerd** [comment]
@Lukasa now you do it via the docker compose file :)

**Comment by Lukasa** [comment]
Oh cool, that works.

**Pull request merged**
