### PR TITLE
docker setup for main nightlies

### PR DESCRIPTION
**Pull request by weissi**

### CODE REVIEW

**Review by PeterAdams-A — APPROVED** [review]
Looks good.

**Review by Lukasa — APPROVED** [review]

**Comment by tomerd** [comment]
@weissi added "nightly" job, which is failing at this time (needs  #1750 first). I am fine with merging this tho.

**Comment by weissi** [comment]
> @weissi added "nightly" job, which is failing at this time (needs #1750 first). I am fine with merging this tho.

awesome, thanks @tomerd . compiler crash... https://bugs.swift.org/browse/SR-14253

**Comment by weissi** [comment]
Swift compiler still can't compile our tests :(. @tomerd could you raise this with the team? Bugs report is https://bugs.swift.org/browse/SR-14268

**Comment by weissi** [comment]
@Lukasa do we still want to merge this?

**Comment by Lukasa** [comment]
Probably, it's better than the current status quo.

**Comment by weissi** [comment]
@Lukasa sounds good, merged

**Pull request merged**
