### PR TITLE
apply ChannelOptions before channel initializer runs

### LINKED ISSUE #1114: Figure out: Initialiser or options first
swift-nio does initialiser, then channel options. NIOTS does the opposite. We need to figure out what’s right and write tests.

CC @normanmaurer

### PR DESCRIPTION
**Pull request by weissi**
Motivation:

The channel initializers should see the the Channel after the options
have been applied so they can potentially override the options.

Modifications:

Set the options before the channel initialiser rather than after.

Result:

- More sense, more compatibility with Netty
- fixes #1114

### CODE REVIEW

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Pull request merged**
