### PR TITLE
Use actual element count of PriorityQueue for its description

### PR DESCRIPTION
**Pull request by adtrevor**
Use actual element count of `PriorityQueue` for its description

### Motivation:

Currently, `PriorityQueue` uses its understimatedCount property for its `CustomStringConvertible` implementation, this doesn't seem to be correct and not very much useful in a debug context.

### Modifications:

Use `count` instead of `underestimatedCount`

### Result:

The actual count is now used

### CODE REVIEW

**Comment by weissi** [comment]
friendly ping @adtrevor

**Comment by adtrevor** [comment]
@weissi Does this look ok?

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Comment by weissi** [comment]
@adtrevor 

```
20:42:42 Test Case 'PriorityQueueTest.testDescription' started at 2019-12-17 20:42:42.322
20:42:42 /code/Tests/NIOTests/PriorityQueueTests.swift:151: error: PriorityQueueTest.testDescription : XCTAssertEqual failed: ("PriorityQueue(count: 0): []") is not equal to ("PriorityQueue(count: 3): [3, 2, 1]") - 
20:42:42 Test Case 'PriorityQueueTest.testDescription' failed (0.001 seconds)
```

**Comment by weissi** [comment]
@adtrevor also please run scripts/generate_linux_tests.tb, minor formatting diff there

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Pull request merged**
