### PR TITLE
Added test for BufferView custom contains function

### PR DESCRIPTION
**Pull request by anishagg17**
Added test for BufferView custom contains function

### Motivation:

This adds a test for  BufferView custom contains function

### Modifications:

Added `testBufferViewContains()` to `ByteBufferTest` 

### Result:

Doesn't affect any endpoint, only a testing improvement

### CODE REVIEW

**Review by Lukasa — APPROVED** [review]
Thanks for this!

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Review by Lukasa — CHANGES_REQUESTED** [review]
Can you fix up the unit test so it compiles?

**Comment by anishagg17** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by anishagg17** [comment]
For me it is working somehow in my environment


Screenshot 2022-07-26 at 4 51 21 AM

**Comment by dnadoba** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Review by Lukasa — APPROVED** [review]

**Pull request merged**
