### PR TITLE
add 'tty: true' to the docker-compose file (#490)

### PR DESCRIPTION
**Pull request by gavrilaf**
Motivation:

swift-nio example projects (http, echo) don't print anything to the console when running inside docker container because of buffering issue.

Modifications:

Added tty: true to the docker-compose.yaml for http & echo.

Result:

Buffering issue is resolved. http & echo prints logs to the console.

### CODE REVIEW

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
Tagging in @weissi for a quick review as well.

**Comment by weissi** [comment]
lgtm but I think that's probably one for @tomerd

**Comment by tomerd** [comment]
:+1:

**Pull request merged**
