### PR TITLE
override content encoding header value in compressor

### PR DESCRIPTION
**Pull request by ilyapuchka**
Resolves #718

### Motivation:

Content encoding header may contain invalid value if handlers before compressor have already set it.

### Modifications:

Instead of `headers.add` which appends header value use `headers.replaceOrAdd` which replaces existing value

### Result:

If `Content-Encoding` header was set to some `value`, compressor will reset it to the value of compression algorithm it have picked.

### CODE REVIEW

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
Fantastic, thanks @ilyapuchka. We need to back port this to the nio-1.12 branch: do you want to create that back port?

**Comment by ilyapuchka** [comment]
@Lukasa do you mean just a separate PR branched from 1.12?

**Comment by Lukasa** [comment]
Yeah, a PR branched from nio-1.12 that targets nio-1.12. You can even make this easy by cherry picking the merged commit on master, 
https://github.com/apple/swift-nio/commit/b878f06b2079ada6d087ed5acbd25533f60332a3

**Pull request merged**
